# Generated by Django 4.2.17 on 2026-02-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_remove_adminprofile_admin_level_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppointmentAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Appointment Analytics",
                "verbose_name_plural": "Appointment Analytics",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="ConsultationAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Analytics",
                "verbose_name_plural": "Consultation Analytics",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="DashboardStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboard",
                "permissions": [("view_dashboard", "Can view analytics dashboard")],
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="RevenueAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Revenue Analytics",
                "verbose_name_plural": "Revenue Analytics",
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[],
            options={
                "verbose_name": "User Analytics",
                "verbose_name_plural": "User Analytics",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.user",),
        ),
    ]
