# Generated by Django 4.2.17 on 2026-02-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAnalytics",
        ),
    ]
