/**
 * DATASET_SYMPTOMS
 * ─────────────────
 * All 317 symptoms from the backend healthcare dataset (healthcare_data.csv).
 * Each entry matches the backend Symptom model structure:
 *   code         → exact dataset column name (used as symptom identifier sent to the API)
 *   name         → human-readable display name
 *   category     → matches backend CATEGORY_CHOICES:
 *                  general | respiratory | digestive | cardiovascular |
 *                  neurological | musculoskeletal | skin | mental |
 *                  urinary | eye | ear | reproductive | other
 *   body_part    → maps to the BODY_PARTS filter in SymptomChecker UI
 */

export const DATASET_SYMPTOMS = [
  // ── Mental Health ──
  { id: 'anxiety and nervousness', code: 'anxiety and nervousness', name: 'Anxiety And Nervousness', category: 'mental', body_part: 'general' },
  { id: 'depression', code: 'depression', name: 'Depression', category: 'mental', body_part: 'general' },
  { id: 'depressive or psychotic symptoms', code: 'depressive or psychotic symptoms', name: 'Depressive Or Psychotic Symptoms', category: 'mental', body_part: 'general' },
  { id: 'insomnia', code: 'insomnia', name: 'Insomnia', category: 'mental', body_part: 'general' },
  { id: 'emotional symptoms', code: 'emotional symptoms', name: 'Emotional Symptoms', category: 'mental', body_part: 'general' },
  { id: 'hostile behavior', code: 'hostile behavior', name: 'Hostile Behavior', category: 'mental', body_part: 'general' },
  { id: 'drug abuse', code: 'drug abuse', name: 'Drug Abuse', category: 'mental', body_part: 'general' },
  { id: 'abusing alcohol', code: 'abusing alcohol', name: 'Abusing Alcohol', category: 'mental', body_part: 'general' },
  { id: 'restlessness', code: 'restlessness', name: 'Restlessness', category: 'mental', body_part: 'general' },
  { id: 'loss of sensation', code: 'loss of sensation', name: 'Loss Of Sensation', category: 'mental', body_part: 'general' },
  { id: 'disturbance of memory', code: 'disturbance of memory', name: 'Disturbance Of Memory', category: 'mental', body_part: 'general' },
  { id: 'fears and phobias', code: 'fears and phobias', name: 'Fears And Phobias', category: 'mental', body_part: 'general' },
  { id: 'obsessions and compulsions', code: 'obsessions and compulsions', name: 'Obsessions And Compulsions', category: 'mental', body_part: 'general' },
  { id: 'antisocial behavior', code: 'antisocial behavior', name: 'Antisocial Behavior', category: 'mental', body_part: 'general' },
  { id: 'temper problems', code: 'temper problems', name: 'Temper Problems', category: 'mental', body_part: 'general' },
  { id: 'hysterical behavior', code: 'hysterical behavior', name: 'Hysterical Behavior', category: 'mental', body_part: 'general' },
  { id: 'delusions or hallucinations', code: 'delusions or hallucinations', name: 'Delusions Or Hallucinations', category: 'mental', body_part: 'general' },
  { id: 'nightmares', code: 'nightmares', name: 'Nightmares', category: 'mental', body_part: 'general' },
  { id: 'sleepwalking', code: 'sleepwalking', name: 'Sleepwalking', category: 'mental', body_part: 'general' },
  { id: 'low self-esteem', code: 'low self-esteem', name: 'Low Self-esteem', category: 'mental', body_part: 'general' },
  { id: 'excessive anger', code: 'excessive anger', name: 'Excessive Anger', category: 'mental', body_part: 'general' },
  { id: 'loss of sex drive', code: 'loss of sex drive', name: 'Loss Of Sex Drive', category: 'mental', body_part: 'general' },
  { id: 'problems with orgasm', code: 'problems with orgasm', name: 'Problems With Orgasm', category: 'mental', body_part: 'general' },

  // ── Cardiovascular ──
  { id: 'sharp chest pain', code: 'sharp chest pain', name: 'Sharp Chest Pain', category: 'cardiovascular', body_part: 'chest' },
  { id: 'chest tightness', code: 'chest tightness', name: 'Chest Tightness', category: 'cardiovascular', body_part: 'chest' },
  { id: 'palpitations', code: 'palpitations', name: 'Palpitations', category: 'cardiovascular', body_part: 'heart' },
  { id: 'irregular heartbeat', code: 'irregular heartbeat', name: 'Irregular Heartbeat', category: 'cardiovascular', body_part: 'heart' },
  { id: 'decreased heart rate', code: 'decreased heart rate', name: 'Decreased Heart Rate', category: 'cardiovascular', body_part: 'heart' },
  { id: 'increased heart rate', code: 'increased heart rate', name: 'Increased Heart Rate', category: 'cardiovascular', body_part: 'heart' },
  { id: 'burning chest pain', code: 'burning chest pain', name: 'Burning Chest Pain', category: 'cardiovascular', body_part: 'chest' },
  { id: 'peripheral edema', code: 'peripheral edema', name: 'Peripheral Edema', category: 'cardiovascular', body_part: 'legs' },
  { id: 'poor circulation', code: 'poor circulation', name: 'Poor Circulation', category: 'cardiovascular', body_part: 'general' },

  // ── Respiratory ──
  { id: 'shortness of breath', code: 'shortness of breath', name: 'Shortness Of Breath', category: 'respiratory', body_part: 'chest' },
  { id: 'breathing fast', code: 'breathing fast', name: 'Breathing Fast', category: 'respiratory', body_part: 'chest' },
  { id: 'cough', code: 'cough', name: 'Cough', category: 'respiratory', body_part: 'chest' },
  { id: 'wheezing', code: 'wheezing', name: 'Wheezing', category: 'respiratory', body_part: 'chest' },
  { id: 'difficulty breathing', code: 'difficulty breathing', name: 'Difficulty Breathing', category: 'respiratory', body_part: 'chest' },
  { id: 'congestion in chest', code: 'congestion in chest', name: 'Congestion In Chest', category: 'respiratory', body_part: 'chest' },
  { id: 'pus in sputum', code: 'pus in sputum', name: 'Pus In Sputum', category: 'respiratory', body_part: 'chest' },
  { id: 'coughing up sputum', code: 'coughing up sputum', name: 'Coughing Up Sputum', category: 'respiratory', body_part: 'chest' },
  { id: 'hemoptysis', code: 'hemoptysis', name: 'Hemoptysis', category: 'respiratory', body_part: 'chest' },
  { id: 'apnea', code: 'apnea', name: 'Apnea', category: 'respiratory', body_part: 'chest' },
  { id: 'abnormal breathing sounds', code: 'abnormal breathing sounds', name: 'Abnormal Breathing Sounds', category: 'respiratory', body_part: 'chest' },
  { id: 'hurts to breath', code: 'hurts to breath', name: 'Hurts To Breathe', category: 'respiratory', body_part: 'chest' },
  { id: 'nasal congestion', code: 'nasal congestion', name: 'Nasal Congestion', category: 'respiratory', body_part: 'nose' },
  { id: 'sinus congestion', code: 'sinus congestion', name: 'Sinus Congestion', category: 'respiratory', body_part: 'nose' },
  { id: 'painful sinuses', code: 'painful sinuses', name: 'Painful Sinuses', category: 'respiratory', body_part: 'nose' },
  { id: 'nosebleed', code: 'nosebleed', name: 'Nosebleed', category: 'respiratory', body_part: 'nose' },
  { id: 'coryza', code: 'coryza', name: 'Coryza', category: 'respiratory', body_part: 'nose' },
  { id: 'sneezing', code: 'sneezing', name: 'Sneezing', category: 'respiratory', body_part: 'nose' },
  { id: 'nose deformity', code: 'nose deformity', name: 'Nose Deformity', category: 'respiratory', body_part: 'nose' },
  { id: 'sore in nose', code: 'sore in nose', name: 'Sore In Nose', category: 'respiratory', body_part: 'nose' },
  { id: 'rib pain', code: 'rib pain', name: 'Rib Pain', category: 'respiratory', body_part: 'chest' },

  // ── Throat & Mouth ──
  { id: 'hoarse voice', code: 'hoarse voice', name: 'Hoarse Voice', category: 'other', body_part: 'throat' },
  { id: 'sore throat', code: 'sore throat', name: 'Sore Throat', category: 'other', body_part: 'throat' },
  { id: 'difficulty speaking', code: 'difficulty speaking', name: 'Difficulty Speaking', category: 'other', body_part: 'throat' },
  { id: 'throat swelling', code: 'throat swelling', name: 'Throat Swelling', category: 'other', body_part: 'throat' },
  { id: 'lump in throat', code: 'lump in throat', name: 'Lump In Throat', category: 'other', body_part: 'throat' },
  { id: 'throat feels tight', code: 'throat feels tight', name: 'Throat Feels Tight', category: 'other', body_part: 'throat' },
  { id: 'difficulty in swallowing', code: 'difficulty in swallowing', name: 'Difficulty In Swallowing', category: 'other', body_part: 'throat' },
  { id: 'swollen or red tonsils', code: 'swollen or red tonsils', name: 'Swollen Or Red Tonsils', category: 'other', body_part: 'throat' },
  { id: 'throat irritation', code: 'throat irritation', name: 'Throat Irritation', category: 'other', body_part: 'throat' },
  { id: 'throat redness', code: 'throat redness', name: 'Throat Redness', category: 'other', body_part: 'throat' },
  { id: 'swollen tongue', code: 'swollen tongue', name: 'Swollen Tongue', category: 'other', body_part: 'throat' },
  { id: 'drainage in throat', code: 'drainage in throat', name: 'Drainage In Throat', category: 'other', body_part: 'throat' },
  { id: 'toothache', code: 'toothache', name: 'Toothache', category: 'other', body_part: 'throat' },
  { id: 'facial pain', code: 'facial pain', name: 'Facial Pain', category: 'other', body_part: 'head' },
  { id: 'mouth ulcer', code: 'mouth ulcer', name: 'Mouth Ulcer', category: 'other', body_part: 'throat' },
  { id: 'dry lips', code: 'dry lips', name: 'Dry Lips', category: 'other', body_part: 'throat' },
  { id: 'lip swelling', code: 'lip swelling', name: 'Lip Swelling', category: 'other', body_part: 'throat' },
  { id: 'lip sore', code: 'lip sore', name: 'Lip Sore', category: 'other', body_part: 'throat' },
  { id: 'mouth dryness', code: 'mouth dryness', name: 'Mouth Dryness', category: 'other', body_part: 'throat' },
  { id: 'mouth pain', code: 'mouth pain', name: 'Mouth Pain', category: 'other', body_part: 'throat' },
  { id: 'bleeding in mouth', code: 'bleeding in mouth', name: 'Bleeding In Mouth', category: 'other', body_part: 'throat' },
  { id: 'bleeding gums', code: 'bleeding gums', name: 'Bleeding Gums', category: 'other', body_part: 'throat' },
  { id: 'pain in gums', code: 'pain in gums', name: 'Pain In Gums', category: 'other', body_part: 'throat' },
  { id: 'gum pain', code: 'gum pain', name: 'Gum Pain', category: 'other', body_part: 'throat' },
  { id: 'tongue lesions', code: 'tongue lesions', name: 'Tongue Lesions', category: 'other', body_part: 'throat' },
  { id: 'abnormal appearing tongue', code: 'abnormal appearing tongue', name: 'Abnormal Appearing Tongue', category: 'other', body_part: 'throat' },
  { id: 'tongue pain', code: 'tongue pain', name: 'Tongue Pain', category: 'other', body_part: 'throat' },
  { id: 'tongue bleeding', code: 'tongue bleeding', name: 'Tongue Bleeding', category: 'other', body_part: 'throat' },
  { id: 'jaw swelling', code: 'jaw swelling', name: 'Jaw Swelling', category: 'other', body_part: 'head' },
  { id: 'jaw pain', code: 'jaw pain', name: 'Jaw Pain', category: 'other', body_part: 'head' },
  { id: 'lump over jaw', code: 'lump over jaw', name: 'Lump Over Jaw', category: 'other', body_part: 'head' },
  { id: 'stuttering or stammering', code: 'stuttering or stammering', name: 'Stuttering Or Stammering', category: 'other', body_part: 'throat' },
  { id: 'disturbance of smell or taste', code: 'disturbance of smell or taste', name: 'Disturbance Of Smell Or Taste', category: 'other', body_part: 'head' },

  // ── Eye ──
  { id: 'eye deviation', code: 'eye deviation', name: 'Eye Deviation', category: 'eye', body_part: 'eyes' },
  { id: 'diminished vision', code: 'diminished vision', name: 'Diminished Vision', category: 'eye', body_part: 'eyes' },
  { id: 'double vision', code: 'double vision', name: 'Double Vision', category: 'eye', body_part: 'eyes' },
  { id: 'cross-eyed', code: 'cross-eyed', name: 'Cross-eyed', category: 'eye', body_part: 'eyes' },
  { id: 'symptoms of eye', code: 'symptoms of eye', name: 'Symptoms Of Eye', category: 'eye', body_part: 'eyes' },
  { id: 'pain in eye', code: 'pain in eye', name: 'Pain In Eye', category: 'eye', body_part: 'eyes' },
  { id: 'eye moves abnormally', code: 'eye moves abnormally', name: 'Eye Moves Abnormally', category: 'eye', body_part: 'eyes' },
  { id: 'abnormal movement of eyelid', code: 'abnormal movement of eyelid', name: 'Abnormal Movement Of Eyelid', category: 'eye', body_part: 'eyes' },
  { id: 'foreign body sensation in eye', code: 'foreign body sensation in eye', name: 'Foreign Body Sensation In Eye', category: 'eye', body_part: 'eyes' },
  { id: 'spots or clouds in vision', code: 'spots or clouds in vision', name: 'Spots Or Clouds In Vision', category: 'eye', body_part: 'eyes' },
  { id: 'eye redness', code: 'eye redness', name: 'Eye Redness', category: 'eye', body_part: 'eyes' },
  { id: 'lacrimation', code: 'lacrimation', name: 'Lacrimation', category: 'eye', body_part: 'eyes' },
  { id: 'itchiness of eye', code: 'itchiness of eye', name: 'Itchiness Of Eye', category: 'eye', body_part: 'eyes' },
  { id: 'blindness', code: 'blindness', name: 'Blindness', category: 'eye', body_part: 'eyes' },
  { id: 'eye burns or stings', code: 'eye burns or stings', name: 'Eye Burns Or Stings', category: 'eye', body_part: 'eyes' },
  { id: 'itchy eyelid', code: 'itchy eyelid', name: 'Itchy Eyelid', category: 'eye', body_part: 'eyes' },
  { id: 'white discharge from eye', code: 'white discharge from eye', name: 'White Discharge From Eye', category: 'eye', body_part: 'eyes' },
  { id: 'bleeding from eye', code: 'bleeding from eye', name: 'Bleeding From Eye', category: 'eye', body_part: 'eyes' },
  { id: 'mass on eyelid', code: 'mass on eyelid', name: 'Mass On Eyelid', category: 'eye', body_part: 'eyes' },
  { id: 'swollen eye', code: 'swollen eye', name: 'Swollen Eye', category: 'eye', body_part: 'eyes' },
  { id: 'eyelid swelling', code: 'eyelid swelling', name: 'Eyelid Swelling', category: 'eye', body_part: 'eyes' },
  { id: 'eyelid lesion or rash', code: 'eyelid lesion or rash', name: 'Eyelid Lesion Or Rash', category: 'eye', body_part: 'eyes' },
  { id: 'eyelid retracted', code: 'eyelid retracted', name: 'Eyelid Retracted', category: 'eye', body_part: 'eyes' },
  { id: 'cloudy eye', code: 'cloudy eye', name: 'Cloudy Eye', category: 'eye', body_part: 'eyes' },
  { id: 'eye strain', code: 'eye strain', name: 'Eye Strain', category: 'eye', body_part: 'eyes' },

  // ── Ear ──
  { id: 'diminished hearing', code: 'diminished hearing', name: 'Diminished Hearing', category: 'ear', body_part: 'ears' },
  { id: 'pus draining from ear', code: 'pus draining from ear', name: 'Pus Draining From Ear', category: 'ear', body_part: 'ears' },
  { id: 'ear pain', code: 'ear pain', name: 'Ear Pain', category: 'ear', body_part: 'ears' },
  { id: 'ringing in ear', code: 'ringing in ear', name: 'Ringing In Ear', category: 'ear', body_part: 'ears' },
  { id: 'plugged feeling in ear', code: 'plugged feeling in ear', name: 'Plugged Feeling In Ear', category: 'ear', body_part: 'ears' },
  { id: 'itchy ear(s)', code: 'itchy ear(s)', name: 'Itchy Ear(s)', category: 'ear', body_part: 'ears' },
  { id: 'fluid in ear', code: 'fluid in ear', name: 'Fluid In Ear', category: 'ear', body_part: 'ears' },
  { id: 'redness in ear', code: 'redness in ear', name: 'Redness In Ear', category: 'ear', body_part: 'ears' },
  { id: 'pulling at ears', code: 'pulling at ears', name: 'Pulling At Ears', category: 'ear', body_part: 'ears' },
  { id: 'bleeding from ear', code: 'bleeding from ear', name: 'Bleeding From Ear', category: 'ear', body_part: 'ears' },
  { id: 'mass on ear', code: 'mass on ear', name: 'Mass On Ear', category: 'ear', body_part: 'ears' },
  { id: 'abnormal size or shape of ear', code: 'abnormal size or shape of ear', name: 'Abnormal Size Or Shape Of Ear', category: 'ear', body_part: 'ears' },

  // ── Neurological ──
  { id: 'dizziness', code: 'dizziness', name: 'Dizziness', category: 'neurological', body_part: 'head' },
  { id: 'abnormal involuntary movements', code: 'abnormal involuntary movements', name: 'Abnormal Involuntary Movements', category: 'neurological', body_part: 'general' },
  { id: 'fainting', code: 'fainting', name: 'Fainting', category: 'neurological', body_part: 'general' },
  { id: 'headache', code: 'headache', name: 'Headache', category: 'neurological', body_part: 'head' },
  { id: 'focal weakness', code: 'focal weakness', name: 'Focal Weakness', category: 'neurological', body_part: 'general' },
  { id: 'slurring words', code: 'slurring words', name: 'Slurring Words', category: 'neurological', body_part: 'head' },
  { id: 'symptoms of the face', code: 'symptoms of the face', name: 'Symptoms Of The Face', category: 'neurological', body_part: 'head' },
  { id: 'paresthesia', code: 'paresthesia', name: 'Paresthesia', category: 'neurological', body_part: 'general' },
  { id: 'seizures', code: 'seizures', name: 'Seizures', category: 'neurological', body_part: 'general' },
  { id: 'frontal headache', code: 'frontal headache', name: 'Frontal Headache', category: 'neurological', body_part: 'head' },
  { id: 'pupils unequal', code: 'pupils unequal', name: 'Pupils Unequal', category: 'neurological', body_part: 'head' },
  { id: 'thirst', code: 'thirst', name: 'Thirst', category: 'neurological', body_part: 'general' },

  // ── Digestive ──
  { id: 'blood in stool', code: 'blood in stool', name: 'Blood In Stool', category: 'digestive', body_part: 'stomach' },
  { id: 'flatulence', code: 'flatulence', name: 'Flatulence', category: 'digestive', body_part: 'stomach' },
  { id: 'jaundice', code: 'jaundice', name: 'Jaundice', category: 'digestive', body_part: 'stomach' },
  { id: 'sharp abdominal pain', code: 'sharp abdominal pain', name: 'Sharp Abdominal Pain', category: 'digestive', body_part: 'stomach' },
  { id: 'vomiting', code: 'vomiting', name: 'Vomiting', category: 'digestive', body_part: 'stomach' },
  { id: 'nausea', code: 'nausea', name: 'Nausea', category: 'digestive', body_part: 'stomach' },
  { id: 'diarrhea', code: 'diarrhea', name: 'Diarrhea', category: 'digestive', body_part: 'stomach' },
  { id: 'lower abdominal pain', code: 'lower abdominal pain', name: 'Lower Abdominal Pain', category: 'digestive', body_part: 'stomach' },
  { id: 'infant spitting up', code: 'infant spitting up', name: 'Infant Spitting Up', category: 'digestive', body_part: 'stomach' },
  { id: 'vomiting blood', code: 'vomiting blood', name: 'Vomiting Blood', category: 'digestive', body_part: 'stomach' },
  { id: 'regurgitation', code: 'regurgitation', name: 'Regurgitation', category: 'digestive', body_part: 'stomach' },
  { id: 'burning abdominal pain', code: 'burning abdominal pain', name: 'Burning Abdominal Pain', category: 'digestive', body_part: 'stomach' },
  { id: 'heartburn', code: 'heartburn', name: 'Heartburn', category: 'digestive', body_part: 'stomach' },
  { id: 'upper abdominal pain', code: 'upper abdominal pain', name: 'Upper Abdominal Pain', category: 'digestive', body_part: 'stomach' },
  { id: 'stomach bloating', code: 'stomach bloating', name: 'Stomach Bloating', category: 'digestive', body_part: 'stomach' },
  { id: 'changes in stool appearance', code: 'changes in stool appearance', name: 'Changes In Stool Appearance', category: 'digestive', body_part: 'stomach' },
  { id: 'swollen abdomen', code: 'swollen abdomen', name: 'Swollen Abdomen', category: 'digestive', body_part: 'stomach' },
  { id: 'abdominal distention', code: 'abdominal distention', name: 'Abdominal Distention', category: 'digestive', body_part: 'stomach' },
  { id: 'regurgitation.1', code: 'regurgitation.1', name: 'Regurgitation (Acid)', category: 'digestive', body_part: 'stomach' },
  { id: 'melena', code: 'melena', name: 'Melena', category: 'digestive', body_part: 'stomach' },
  { id: 'rectal bleeding', code: 'rectal bleeding', name: 'Rectal Bleeding', category: 'digestive', body_part: 'stomach' },
  { id: 'constipation', code: 'constipation', name: 'Constipation', category: 'digestive', body_part: 'stomach' },
  { id: 'pain of the anus', code: 'pain of the anus', name: 'Pain Of The Anus', category: 'digestive', body_part: 'stomach' },
  { id: 'mass or swelling around the anus', code: 'mass or swelling around the anus', name: 'Mass Or Swelling Around The Anus', category: 'digestive', body_part: 'stomach' },
  { id: 'incontinence of stool', code: 'incontinence of stool', name: 'Incontinence Of Stool', category: 'digestive', body_part: 'stomach' },
  { id: 'discharge in stools', code: 'discharge in stools', name: 'Discharge In Stools', category: 'digestive', body_part: 'stomach' },
  { id: 'difficulty eating', code: 'difficulty eating', name: 'Difficulty Eating', category: 'digestive', body_part: 'stomach' },
  { id: 'infant feeding problem', code: 'infant feeding problem', name: 'Infant Feeding Problem', category: 'digestive', body_part: 'stomach' },
  { id: 'symptoms of infants', code: 'symptoms of infants', name: 'Symptoms Of Infants', category: 'digestive', body_part: 'general' },
  { id: 'irritable infant', code: 'irritable infant', name: 'Irritable Infant', category: 'digestive', body_part: 'general' },

  // ── Musculoskeletal ──
  { id: 'elbow weakness', code: 'elbow weakness', name: 'Elbow Weakness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'back weakness', code: 'back weakness', name: 'Back Weakness', category: 'musculoskeletal', body_part: 'back' },
  { id: 'leg pain', code: 'leg pain', name: 'Leg Pain', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'hip pain', code: 'hip pain', name: 'Hip Pain', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'back pain', code: 'back pain', name: 'Back Pain', category: 'musculoskeletal', body_part: 'back' },
  { id: 'neck pain', code: 'neck pain', name: 'Neck Pain', category: 'musculoskeletal', body_part: 'back' },
  { id: 'low back pain', code: 'low back pain', name: 'Low Back Pain', category: 'musculoskeletal', body_part: 'back' },
  { id: 'knee pain', code: 'knee pain', name: 'Knee Pain', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'foot or toe pain', code: 'foot or toe pain', name: 'Foot Or Toe Pain', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'ankle pain', code: 'ankle pain', name: 'Ankle Pain', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'bones are painful', code: 'bones are painful', name: 'Bones Are Painful', category: 'musculoskeletal', body_part: 'general' },
  { id: 'knee weakness', code: 'knee weakness', name: 'Knee Weakness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'elbow pain', code: 'elbow pain', name: 'Elbow Pain', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'knee swelling', code: 'knee swelling', name: 'Knee Swelling', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'knee lump or mass', code: 'knee lump or mass', name: 'Knee Lump Or Mass', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'problems with movement', code: 'problems with movement', name: 'Problems With Movement', category: 'musculoskeletal', body_part: 'general' },
  { id: 'knee stiffness or tightness', code: 'knee stiffness or tightness', name: 'Knee Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'leg swelling', code: 'leg swelling', name: 'Leg Swelling', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'foot or toe swelling', code: 'foot or toe swelling', name: 'Foot Or Toe Swelling', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'muscle pain', code: 'muscle pain', name: 'Muscle Pain', category: 'musculoskeletal', body_part: 'general' },
  { id: 'shoulder pain', code: 'shoulder pain', name: 'Shoulder Pain', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'shoulder stiffness or tightness', code: 'shoulder stiffness or tightness', name: 'Shoulder Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'shoulder weakness', code: 'shoulder weakness', name: 'Shoulder Weakness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'arm cramps or spasms', code: 'arm cramps or spasms', name: 'Arm Cramps Or Spasms', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'shoulder swelling', code: 'shoulder swelling', name: 'Shoulder Swelling', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'leg cramps or spasms', code: 'leg cramps or spasms', name: 'Leg Cramps Or Spasms', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'ache all over', code: 'ache all over', name: 'Ache All Over', category: 'musculoskeletal', body_part: 'general' },
  { id: 'lower body pain', code: 'lower body pain', name: 'Lower Body Pain', category: 'musculoskeletal', body_part: 'general' },
  { id: 'cramps and spasms', code: 'cramps and spasms', name: 'Cramps And Spasms', category: 'musculoskeletal', body_part: 'general' },
  { id: 'joint pain', code: 'joint pain', name: 'Joint Pain', category: 'musculoskeletal', body_part: 'general' },
  { id: 'muscle stiffness or tightness', code: 'muscle stiffness or tightness', name: 'Muscle Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'general' },
  { id: 'hand or finger lump or mass', code: 'hand or finger lump or mass', name: 'Hand Or Finger Lump Or Mass', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'hand or finger pain', code: 'hand or finger pain', name: 'Hand Or Finger Pain', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'wrist pain', code: 'wrist pain', name: 'Wrist Pain', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'hand or finger swelling', code: 'hand or finger swelling', name: 'Hand Or Finger Swelling', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'arm pain', code: 'arm pain', name: 'Arm Pain', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'wrist swelling', code: 'wrist swelling', name: 'Wrist Swelling', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'arm stiffness or tightness', code: 'arm stiffness or tightness', name: 'Arm Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'arm swelling', code: 'arm swelling', name: 'Arm Swelling', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'hand or finger stiffness or tightness', code: 'hand or finger stiffness or tightness', name: 'Hand Or Finger Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'wrist stiffness or tightness', code: 'wrist stiffness or tightness', name: 'Wrist Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'shoulder cramps or spasms', code: 'shoulder cramps or spasms', name: 'Shoulder Cramps Or Spasms', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'joint stiffness or tightness', code: 'joint stiffness or tightness', name: 'Joint Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'general' },
  { id: 'wrist weakness', code: 'wrist weakness', name: 'Wrist Weakness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'low back weakness', code: 'low back weakness', name: 'Low Back Weakness', category: 'musculoskeletal', body_part: 'back' },
  { id: 'elbow cramps or spasms', code: 'elbow cramps or spasms', name: 'Elbow Cramps Or Spasms', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'back cramps or spasms', code: 'back cramps or spasms', name: 'Back Cramps Or Spasms', category: 'musculoskeletal', body_part: 'back' },
  { id: 'stiffness all over', code: 'stiffness all over', name: 'Stiffness All Over', category: 'musculoskeletal', body_part: 'general' },
  { id: 'muscle cramps, contractures, or spasms', code: 'muscle cramps, contractures, or spasms', name: 'Muscle Cramps, Contractures, Or Spasms', category: 'musculoskeletal', body_part: 'general' },
  { id: 'low back cramps or spasms', code: 'low back cramps or spasms', name: 'Low Back Cramps Or Spasms', category: 'musculoskeletal', body_part: 'back' },
  { id: 'back mass or lump', code: 'back mass or lump', name: 'Back Mass Or Lump', category: 'musculoskeletal', body_part: 'back' },
  { id: 'muscle weakness', code: 'muscle weakness', name: 'Muscle Weakness', category: 'musculoskeletal', body_part: 'general' },
  { id: 'joint swelling', code: 'joint swelling', name: 'Joint Swelling', category: 'musculoskeletal', body_part: 'general' },
  { id: 'back stiffness or tightness', code: 'back stiffness or tightness', name: 'Back Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'back' },
  { id: 'wrist lump or mass', code: 'wrist lump or mass', name: 'Wrist Lump Or Mass', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'low back stiffness or tightness', code: 'low back stiffness or tightness', name: 'Low Back Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'back' },
  { id: 'posture problems', code: 'posture problems', name: 'Posture Problems', category: 'musculoskeletal', body_part: 'back' },
  { id: 'hip weakness', code: 'hip weakness', name: 'Hip Weakness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'back swelling', code: 'back swelling', name: 'Back Swelling', category: 'musculoskeletal', body_part: 'back' },
  { id: 'ankle stiffness or tightness', code: 'ankle stiffness or tightness', name: 'Ankle Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'ankle weakness', code: 'ankle weakness', name: 'Ankle Weakness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'neck weakness', code: 'neck weakness', name: 'Neck Weakness', category: 'musculoskeletal', body_part: 'back' },
  { id: 'neck stiffness or tightness', code: 'neck stiffness or tightness', name: 'Neck Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'back' },
  { id: 'neck swelling', code: 'neck swelling', name: 'Neck Swelling', category: 'musculoskeletal', body_part: 'back' },
  { id: 'neck mass', code: 'neck mass', name: 'Neck Mass', category: 'musculoskeletal', body_part: 'back' },
  { id: 'neck cramps or spasms', code: 'neck cramps or spasms', name: 'Neck Cramps Or Spasms', category: 'musculoskeletal', body_part: 'back' },
  { id: 'shoulder lump or mass', code: 'shoulder lump or mass', name: 'Shoulder Lump Or Mass', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'elbow swelling', code: 'elbow swelling', name: 'Elbow Swelling', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'elbow stiffness or tightness', code: 'elbow stiffness or tightness', name: 'Elbow Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'elbow lump or mass', code: 'elbow lump or mass', name: 'Elbow Lump Or Mass', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'foot or toe cramps or spasms', code: 'foot or toe cramps or spasms', name: 'Foot Or Toe Cramps Or Spasms', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'foot or toe lump or mass', code: 'foot or toe lump or mass', name: 'Foot Or Toe Lump Or Mass', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'low back swelling', code: 'low back swelling', name: 'Low Back Swelling', category: 'musculoskeletal', body_part: 'back' },
  { id: 'ankle swelling', code: 'ankle swelling', name: 'Ankle Swelling', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'hip lump or mass', code: 'hip lump or mass', name: 'Hip Lump Or Mass', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'hip swelling', code: 'hip swelling', name: 'Hip Swelling', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'hip stiffness or tightness', code: 'hip stiffness or tightness', name: 'Hip Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'arm weakness', code: 'arm weakness', name: 'Arm Weakness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'arm lump or mass', code: 'arm lump or mass', name: 'Arm Lump Or Mass', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'leg lump or mass', code: 'leg lump or mass', name: 'Leg Lump Or Mass', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'leg stiffness or tightness', code: 'leg stiffness or tightness', name: 'Leg Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'leg weakness', code: 'leg weakness', name: 'Leg Weakness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'hand or finger weakness', code: 'hand or finger weakness', name: 'Hand Or Finger Weakness', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'hand or finger cramps or spasms', code: 'hand or finger cramps or spasms', name: 'Hand Or Finger Cramps Or Spasms', category: 'musculoskeletal', body_part: 'arms' },
  { id: 'knee cramps or spasms', code: 'knee cramps or spasms', name: 'Knee Cramps Or Spasms', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'bowlegged or knock-kneed', code: 'bowlegged or knock-kneed', name: 'Bowlegged Or Knock-kneed', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'foot or toe stiffness or tightness', code: 'foot or toe stiffness or tightness', name: 'Foot Or Toe Stiffness Or Tightness', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'feet turned in', code: 'feet turned in', name: 'Feet Turned In', category: 'musculoskeletal', body_part: 'legs' },
  { id: 'foot or toe weakness', code: 'foot or toe weakness', name: 'Foot Or Toe Weakness', category: 'musculoskeletal', body_part: 'legs' },

  // ── Skin ──
  { id: 'skin swelling', code: 'skin swelling', name: 'Skin Swelling', category: 'skin', body_part: 'skin' },
  { id: 'abnormal appearing skin', code: 'abnormal appearing skin', name: 'Abnormal Appearing Skin', category: 'skin', body_part: 'skin' },
  { id: 'skin lesion', code: 'skin lesion', name: 'Skin Lesion', category: 'skin', body_part: 'skin' },
  { id: 'acne or pimples', code: 'acne or pimples', name: 'Acne Or Pimples', category: 'skin', body_part: 'skin' },
  { id: 'skin growth', code: 'skin growth', name: 'Skin Growth', category: 'skin', body_part: 'skin' },
  { id: 'irregular appearing scalp', code: 'irregular appearing scalp', name: 'Irregular Appearing Scalp', category: 'skin', body_part: 'skin' },
  { id: 'skin moles', code: 'skin moles', name: 'Skin Moles', category: 'skin', body_part: 'skin' },
  { id: 'itching of skin', code: 'itching of skin', name: 'Itching Of Skin', category: 'skin', body_part: 'skin' },
  { id: 'skin dryness, peeling, scaliness, or roughness', code: 'skin dryness, peeling, scaliness, or roughness', name: 'Skin Dryness, Peeling, Scaliness, Or Roughness', category: 'skin', body_part: 'skin' },
  { id: 'skin on arm or hand looks infected', code: 'skin on arm or hand looks infected', name: 'Skin On Arm Or Hand Looks Infected', category: 'skin', body_part: 'skin' },
  { id: 'skin irritation', code: 'skin irritation', name: 'Skin Irritation', category: 'skin', body_part: 'skin' },
  { id: 'itchy scalp', code: 'itchy scalp', name: 'Itchy Scalp', category: 'skin', body_part: 'skin' },
  { id: 'warts', code: 'warts', name: 'Warts', category: 'skin', body_part: 'skin' },
  { id: 'skin rash', code: 'skin rash', name: 'Skin Rash', category: 'skin', body_part: 'skin' },
  { id: 'dry or flaky scalp', code: 'dry or flaky scalp', name: 'Dry Or Flaky Scalp', category: 'skin', body_part: 'skin' },
  { id: 'change in skin mole size or color', code: 'change in skin mole size or color', name: 'Change In Skin Mole Size Or Color', category: 'skin', body_part: 'skin' },
  { id: 'skin on leg or foot looks infected', code: 'skin on leg or foot looks infected', name: 'Skin On Leg Or Foot Looks Infected', category: 'skin', body_part: 'skin' },
  { id: 'skin on arm or hand looks infected', code: 'skin on arm or hand looks infected', name: 'Skin On Arm Or Hand Looks Infected', category: 'skin', body_part: 'skin' },
  { id: 'skin on head or neck looks infected', code: 'skin on head or neck looks infected', name: 'Skin On Head Or Neck Looks Infected', category: 'skin', body_part: 'skin' },
  { id: 'skin oiliness', code: 'skin oiliness', name: 'Skin Oiliness', category: 'skin', body_part: 'skin' },
  { id: 'skin pain', code: 'skin pain', name: 'Skin Pain', category: 'skin', body_part: 'skin' },
  { id: 'muscle swelling', code: 'muscle swelling', name: 'Muscle Swelling', category: 'skin', body_part: 'general' },
  { id: 'allergic reaction', code: 'allergic reaction', name: 'Allergic Reaction', category: 'skin', body_part: 'skin' },
  { id: 'lymphedema', code: 'lymphedema', name: 'Lymphedema', category: 'skin', body_part: 'general' },
  { id: 'swollen lymph nodes', code: 'swollen lymph nodes', name: 'Swollen Lymph Nodes', category: 'skin', body_part: 'general' },
  { id: 'diaper rash', code: 'diaper rash', name: 'Diaper Rash', category: 'skin', body_part: 'skin' },
  { id: 'redness in or around nose', code: 'redness in or around nose', name: 'Redness In Or Around Nose', category: 'skin', body_part: 'skin' },
  { id: 'wrinkles on skin', code: 'wrinkles on skin', name: 'Wrinkles On Skin', category: 'skin', body_part: 'skin' },
  { id: 'unwanted hair', code: 'unwanted hair', name: 'Unwanted Hair', category: 'skin', body_part: 'skin' },
  { id: 'too little hair', code: 'too little hair', name: 'Too Little Hair', category: 'skin', body_part: 'skin' },
  { id: 'irregular appearing nails', code: 'irregular appearing nails', name: 'Irregular Appearing Nails', category: 'skin', body_part: 'skin' },
  { id: 'nailbiting', code: 'nailbiting', name: 'Nailbiting', category: 'skin', body_part: 'skin' },
  { id: 'flushing', code: 'flushing', name: 'Flushing', category: 'skin', body_part: 'skin' },
  { id: 'sweating', code: 'sweating', name: 'Sweating', category: 'skin', body_part: 'general' },

  // ── Urinary ──
  { id: 'retention of urine', code: 'retention of urine', name: 'Retention Of Urine', category: 'urinary', body_part: 'stomach' },
  { id: 'painful urination', code: 'painful urination', name: 'Painful Urination', category: 'urinary', body_part: 'stomach' },
  { id: 'involuntary urination', code: 'involuntary urination', name: 'Involuntary Urination', category: 'urinary', body_part: 'stomach' },
  { id: 'frequent urination', code: 'frequent urination', name: 'Frequent Urination', category: 'urinary', body_part: 'stomach' },
  { id: 'blood in urine', code: 'blood in urine', name: 'Blood In Urine', category: 'urinary', body_part: 'stomach' },
  { id: 'unusual color or odor to urine', code: 'unusual color or odor to urine', name: 'Unusual Color Or Odor To Urine', category: 'urinary', body_part: 'stomach' },
  { id: 'kidney mass', code: 'kidney mass', name: 'Kidney Mass', category: 'urinary', body_part: 'stomach' },
  { id: 'symptoms of the kidneys', code: 'symptoms of the kidneys', name: 'Symptoms Of The Kidneys', category: 'urinary', body_part: 'stomach' },
  { id: 'symptoms of prostate', code: 'symptoms of prostate', name: 'Symptoms Of Prostate', category: 'urinary', body_part: 'stomach' },
  { id: 'pus in urine', code: 'pus in urine', name: 'Pus In Urine', category: 'urinary', body_part: 'stomach' },
  { id: 'polyuria', code: 'polyuria', name: 'Polyuria', category: 'urinary', body_part: 'stomach' },
  { id: 'low urine output', code: 'low urine output', name: 'Low Urine Output', category: 'urinary', body_part: 'stomach' },
  { id: 'excessive urination at night', code: 'excessive urination at night', name: 'Excessive Urination At Night', category: 'urinary', body_part: 'stomach' },
  { id: 'bladder mass', code: 'bladder mass', name: 'Bladder Mass', category: 'urinary', body_part: 'stomach' },
  { id: 'symptoms of bladder', code: 'symptoms of bladder', name: 'Symptoms Of Bladder', category: 'urinary', body_part: 'stomach' },
  { id: 'bedwetting', code: 'bedwetting', name: 'Bedwetting', category: 'urinary', body_part: 'stomach' },
  { id: 'hesitancy', code: 'hesitancy', name: 'Hesitancy', category: 'urinary', body_part: 'stomach' },

  // ── Reproductive ──
  { id: 'vaginal itching', code: 'vaginal itching', name: 'Vaginal Itching', category: 'reproductive', body_part: 'stomach' },
  { id: 'vaginal dryness', code: 'vaginal dryness', name: 'Vaginal Dryness', category: 'reproductive', body_part: 'stomach' },
  { id: 'pain during intercourse', code: 'pain during intercourse', name: 'Pain During Intercourse', category: 'reproductive', body_part: 'stomach' },
  { id: 'vaginal discharge', code: 'vaginal discharge', name: 'Vaginal Discharge', category: 'reproductive', body_part: 'stomach' },
  { id: 'hot flashes', code: 'hot flashes', name: 'Hot Flashes', category: 'reproductive', body_part: 'general' },
  { id: 'intermenstrual bleeding', code: 'intermenstrual bleeding', name: 'Intermenstrual Bleeding', category: 'reproductive', body_part: 'stomach' },
  { id: 'scanty menstrual flow', code: 'scanty menstrual flow', name: 'Scanty Menstrual Flow', category: 'reproductive', body_part: 'stomach' },
  { id: 'vaginal pain', code: 'vaginal pain', name: 'Vaginal Pain', category: 'reproductive', body_part: 'stomach' },
  { id: 'vaginal redness', code: 'vaginal redness', name: 'Vaginal Redness', category: 'reproductive', body_part: 'stomach' },
  { id: 'vulvar irritation', code: 'vulvar irritation', name: 'Vulvar Irritation', category: 'reproductive', body_part: 'stomach' },
  { id: 'bleeding or discharge from nipple', code: 'bleeding or discharge from nipple', name: 'Bleeding Or Discharge From Nipple', category: 'reproductive', body_part: 'chest' },
  { id: 'impotence', code: 'impotence', name: 'Impotence', category: 'reproductive', body_part: 'general' },
  { id: 'pain during pregnancy', code: 'pain during pregnancy', name: 'Pain During Pregnancy', category: 'reproductive', body_part: 'stomach' },
  { id: 'pelvic pain', code: 'pelvic pain', name: 'Pelvic Pain', category: 'reproductive', body_part: 'stomach' },
  { id: 'problems during pregnancy', code: 'problems during pregnancy', name: 'Problems During Pregnancy', category: 'reproductive', body_part: 'stomach' },
  { id: 'spotting or bleeding during pregnancy', code: 'spotting or bleeding during pregnancy', name: 'Spotting Or Bleeding During Pregnancy', category: 'reproductive', body_part: 'stomach' },
  { id: 'symptoms of the scrotum and testes', code: 'symptoms of the scrotum and testes', name: 'Symptoms Of The Scrotum And Testes', category: 'reproductive', body_part: 'stomach' },
  { id: 'swelling of scrotum', code: 'swelling of scrotum', name: 'Swelling Of Scrotum', category: 'reproductive', body_part: 'stomach' },
  { id: 'pain in testicles', code: 'pain in testicles', name: 'Pain In Testicles', category: 'reproductive', body_part: 'stomach' },
  { id: 'mass in scrotum', code: 'mass in scrotum', name: 'Mass In Scrotum', category: 'reproductive', body_part: 'stomach' },
  { id: 'groin mass', code: 'groin mass', name: 'Groin Mass', category: 'reproductive', body_part: 'stomach' },
  { id: 'groin pain', code: 'groin pain', name: 'Groin Pain', category: 'reproductive', body_part: 'stomach' },
  { id: 'problems with shape or size of breast', code: 'problems with shape or size of breast', name: 'Problems With Shape Or Size Of Breast', category: 'reproductive', body_part: 'chest' },
  { id: 'pain or soreness of breast', code: 'pain or soreness of breast', name: 'Pain Or Soreness Of Breast', category: 'reproductive', body_part: 'chest' },
  { id: 'lump or mass of breast', code: 'lump or mass of breast', name: 'Lump Or Mass Of Breast', category: 'reproductive', body_part: 'chest' },
  { id: 'vaginal bleeding after menopause', code: 'vaginal bleeding after menopause', name: 'Vaginal Bleeding After Menopause', category: 'reproductive', body_part: 'stomach' },
  { id: 'infrequent menstruation', code: 'infrequent menstruation', name: 'Infrequent Menstruation', category: 'reproductive', body_part: 'stomach' },
  { id: 'mass on vulva', code: 'mass on vulva', name: 'Mass On Vulva', category: 'reproductive', body_part: 'stomach' },
  { id: 'itching of scrotum', code: 'itching of scrotum', name: 'Itching Of Scrotum', category: 'reproductive', body_part: 'stomach' },
  { id: 'postpartum problems of the breast', code: 'postpartum problems of the breast', name: 'Postpartum Problems Of The Breast', category: 'reproductive', body_part: 'chest' },
  { id: 'long menstrual periods', code: 'long menstrual periods', name: 'Long Menstrual Periods', category: 'reproductive', body_part: 'stomach' },
  { id: 'heavy menstrual flow', code: 'heavy menstrual flow', name: 'Heavy Menstrual Flow', category: 'reproductive', body_part: 'stomach' },
  { id: 'unpredictable menstruation', code: 'unpredictable menstruation', name: 'Unpredictable Menstruation', category: 'reproductive', body_part: 'stomach' },
  { id: 'painful menstruation', code: 'painful menstruation', name: 'Painful Menstruation', category: 'reproductive', body_part: 'stomach' },
  { id: 'infertility', code: 'infertility', name: 'Infertility', category: 'reproductive', body_part: 'general' },
  { id: 'frequent menstruation', code: 'frequent menstruation', name: 'Frequent Menstruation', category: 'reproductive', body_part: 'stomach' },
  { id: 'absence of menstruation', code: 'absence of menstruation', name: 'Absence Of Menstruation', category: 'reproductive', body_part: 'stomach' },
  { id: 'blood clots during menstrual periods', code: 'blood clots during menstrual periods', name: 'Blood Clots During Menstrual Periods', category: 'reproductive', body_part: 'stomach' },
  { id: 'premenstrual tension or irritability', code: 'premenstrual tension or irritability', name: 'Premenstrual Tension Or Irritability', category: 'reproductive', body_part: 'general' },
  { id: 'early or late onset of menopause', code: 'early or late onset of menopause', name: 'Early Or Late Onset Of Menopause', category: 'reproductive', body_part: 'general' },
  { id: 'uterine contractions', code: 'uterine contractions', name: 'Uterine Contractions', category: 'reproductive', body_part: 'stomach' },
  { id: 'recent pregnancy', code: 'recent pregnancy', name: 'Recent Pregnancy', category: 'reproductive', body_part: 'general' },
  { id: 'pelvic pressure', code: 'pelvic pressure', name: 'Pelvic Pressure', category: 'reproductive', body_part: 'stomach' },
  { id: 'penis pain', code: 'penis pain', name: 'Penis Pain', category: 'reproductive', body_part: 'stomach' },
  { id: 'bumps on penis', code: 'bumps on penis', name: 'Bumps On Penis', category: 'reproductive', body_part: 'stomach' },
  { id: 'penis redness', code: 'penis redness', name: 'Penis Redness', category: 'reproductive', body_part: 'stomach' },
  { id: 'penile discharge', code: 'penile discharge', name: 'Penile Discharge', category: 'reproductive', body_part: 'stomach' },
  { id: 'premature ejaculation', code: 'premature ejaculation', name: 'Premature Ejaculation', category: 'reproductive', body_part: 'general' },
  { id: 'vulvar sore', code: 'vulvar sore', name: 'Vulvar Sore', category: 'reproductive', body_part: 'stomach' },
  { id: 'itching of the anus', code: 'itching of the anus', name: 'Itching Of The Anus', category: 'reproductive', body_part: 'stomach' },
  { id: 'irregular belly button', code: 'irregular belly button', name: 'Irregular Belly Button', category: 'reproductive', body_part: 'stomach' },
  { id: 'suprapubic pain', code: 'suprapubic pain', name: 'Suprapubic Pain', category: 'reproductive', body_part: 'stomach' },

  // ── General ──
  { id: 'lack of growth', code: 'lack of growth', name: 'Lack Of Growth', category: 'general', body_part: 'general' },
  { id: 'feeling ill', code: 'feeling ill', name: 'Feeling Ill', category: 'general', body_part: 'general' },
  { id: 'fever', code: 'fever', name: 'Fever', category: 'general', body_part: 'general' },
  { id: 'weakness', code: 'weakness', name: 'Weakness', category: 'general', body_part: 'general' },
  { id: 'fatigue', code: 'fatigue', name: 'Fatigue', category: 'general', body_part: 'general' },
  { id: 'chills', code: 'chills', name: 'Chills', category: 'general', body_part: 'general' },
  { id: 'weight gain', code: 'weight gain', name: 'Weight Gain', category: 'general', body_part: 'general' },
  { id: 'recent weight loss', code: 'recent weight loss', name: 'Recent Weight Loss', category: 'general', body_part: 'general' },
  { id: 'underweight', code: 'underweight', name: 'Underweight', category: 'general', body_part: 'general' },
  { id: 'decreased appetite', code: 'decreased appetite', name: 'Decreased Appetite', category: 'general', body_part: 'general' },
  { id: 'excessive appetite', code: 'excessive appetite', name: 'Excessive Appetite', category: 'general', body_part: 'general' },
  { id: 'feeling cold', code: 'feeling cold', name: 'Feeling Cold', category: 'general', body_part: 'general' },
  { id: 'feeling hot and cold', code: 'feeling hot and cold', name: 'Feeling Hot And Cold', category: 'general', body_part: 'general' },
  { id: 'feeling hot', code: 'feeling hot', name: 'Feeling Hot', category: 'general', body_part: 'general' },
  { id: 'side pain', code: 'side pain', name: 'Side Pain', category: 'general', body_part: 'general' },
  { id: 'flu-like syndrome', code: 'flu-like syndrome', name: 'Flu-like Syndrome', category: 'general', body_part: 'general' },
  { id: 'fluid retention', code: 'fluid retention', name: 'Fluid Retention', category: 'general', body_part: 'general' },
  { id: 'sleepiness', code: 'sleepiness', name: 'Sleepiness', category: 'general', body_part: 'general' },
  { id: 'pallor', code: 'pallor', name: 'Pallor', category: 'general', body_part: 'general' },
  { id: 'excessive growth', code: 'excessive growth', name: 'Excessive Growth', category: 'general', body_part: 'general' },
  { id: 'smoking problems', code: 'smoking problems', name: 'Smoking Problems', category: 'general', body_part: 'general' },
];