# Generated by Django 4.2.17 on 2026-01-25 16:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeviceToken",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        help_text="Firebase Cloud Messaging token", unique=True
                    ),
                ),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web Browser"),
                        ],
                        default="web",
                        max_length=20,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        help_text="User-friendly device name (e.g., 'My Phone')",
                        max_length=100,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True, help_text="Unique device identifier", max_length=255
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Whether this token is still valid"
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time a notification was sent to this device",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_device_tokens",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Appointment Reminder"),
                            ("appointment_confirmed", "Appointment Confirmed"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_rescheduled", "Appointment Rescheduled"),
                            ("medicine_reminder", "Medicine Reminder"),
                            ("medicine_low_stock", "Medicine Low Stock"),
                            ("prescription_ready", "Prescription Ready"),
                            ("health_tip", "Health Tip"),
                            ("health_checkup_reminder", "Health Checkup Reminder"),
                            ("lab_result_ready", "Lab Result Ready"),
                            ("emergency_alert", "Emergency Alert"),
                            ("emergency_contact_alert", "Emergency Contact Alert"),
                            ("welcome", "Welcome"),
                            ("account_update", "Account Update"),
                            ("general", "General"),
                            ("chat_message", "Chat Message"),
                            ("doctor_response", "Doctor Response"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("body", models.TextField(max_length=500)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "channels",
                    models.JSONField(
                        default=list, help_text="Channels used: ['push', 'in_app']"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link to open when notification is tapped",
                        max_length=255,
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data to send with notification",
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("color", models.CharField(blank=True, max_length=20)),
                ("image_url", models.URLField(blank=True)),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When to send the notification (null = immediately)",
                        null=True,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                (
                    "group_key",
                    models.CharField(
                        blank=True,
                        help_text="Group key for collapsible notifications",
                        max_length=100,
                    ),
                ),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of related object (e.g., 'appointment')",
                        max_length=50,
                    ),
                ),
                (
                    "related_object_id",
                    models.CharField(
                        blank=True, help_text="ID of related object", max_length=50
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("push", "Push Notification"),
                            ("in_app", "In-App Notification"),
                            ("sms", "SMS"),
                            ("email", "Email"),
                        ],
                        max_length=20,
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=50)),
                ("error_message", models.TextField(blank=True)),
                (
                    "fcm_message_id",
                    models.CharField(
                        blank=True,
                        help_text="FCM message ID if successful",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "notification_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unique template name (e.g., 'appointment_reminder_1hr')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("appointment_reminder", "Appointment Reminder"),
                            ("appointment_confirmed", "Appointment Confirmed"),
                            ("appointment_cancelled", "Appointment Cancelled"),
                            ("appointment_rescheduled", "Appointment Rescheduled"),
                            ("medicine_reminder", "Medicine Reminder"),
                            ("medicine_low_stock", "Medicine Low Stock"),
                            ("prescription_ready", "Prescription Ready"),
                            ("health_tip", "Health Tip"),
                            ("health_checkup_reminder", "Health Checkup Reminder"),
                            ("lab_result_ready", "Lab Result Ready"),
                            ("emergency_alert", "Emergency Alert"),
                            ("emergency_contact_alert", "Emergency Contact Alert"),
                            ("welcome", "Welcome"),
                            ("account_update", "Account Update"),
                            ("general", "General"),
                            ("chat_message", "Chat Message"),
                            ("doctor_response", "Doctor Response"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("title_en", models.CharField(max_length=100)),
                ("title_te", models.CharField(blank=True, max_length=100)),
                ("title_hi", models.CharField(blank=True, max_length=100)),
                ("body_en", models.TextField(max_length=500)),
                ("body_te", models.TextField(blank=True, max_length=500)),
                ("body_hi", models.TextField(blank=True, max_length=500)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        help_text="Deep link or URL to open (e.g., '/appointments/{id}')",
                        max_length=255,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name for the notification",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True,
                        help_text="Color code (e.g., '#4CAF50')",
                        max_length=20,
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Optional image to show in notification"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["notification_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notifications_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch to enable/disable all notifications",
                    ),
                ),
                (
                    "push_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable push notifications"
                    ),
                ),
                (
                    "quiet_hours_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable quiet hours (no non-urgent notifications)",
                    ),
                ),
                (
                    "quiet_hours_start",
                    models.TimeField(
                        default="22:00", help_text="Quiet hours start time"
                    ),
                ),
                (
                    "quiet_hours_end",
                    models.TimeField(default="07:00", help_text="Quiet hours end time"),
                ),
                (
                    "type_preferences",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-type notification preferences",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_user_preferences",
            },
        ),
        migrations.CreateModel(
            name="ScheduledNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("custom", "Custom"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                (
                    "scheduled_time",
                    models.TimeField(help_text="Time of day to send notification"),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Days of week (0=Monday, 6=Sunday)",
                    ),
                ),
                (
                    "day_of_month",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(31),
                        ],
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="When to stop sending (null = forever)",
                        null=True,
                    ),
                ),
                (
                    "custom_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Custom data to include in notification",
                    ),
                ),
                ("related_object_type", models.CharField(blank=True, max_length=50)),
                ("related_object_id", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent_at", models.DateTimeField(blank=True, null=True)),
                ("next_send_at", models.DateTimeField(blank=True, null=True)),
                ("total_sent", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_notifications",
                        to="notifications.notificationtemplate",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scheduled_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_scheduled",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.AddIndex(
            model_name="notificationtemplate",
            index=models.Index(
                fields=["notification_type", "is_active"],
                name="notificatio_notific_67abf3_idx",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="device_token",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="notifications.devicetoken",
            ),
        ),
        migrations.AddField(
            model_name="notificationlog",
            name="notification",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="notifications.notification",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.notificationtemplate",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="devicetoken",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="device_tokens",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["user", "is_active"], name="notificatio_user_id_71ca40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="schedulednotification",
            index=models.Index(
                fields=["next_send_at", "is_active"],
                name="notificatio_next_se_ab5606_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["notification", "-created_at"],
                name="notificatio_notific_0c4895_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notificationlog",
            index=models.Index(
                fields=["success", "-created_at"], name="notificatio_success_bf7856_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "status", "-created_at"],
                name="notificatio_user_id_a34568_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "read_at"], name="notificatio_user_id_6c7360_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["notification_type", "status"],
                name="notificatio_notific_21f913_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["scheduled_at", "status"], name="notificatio_schedul_c045c8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["related_object_type", "related_object_id"],
                name="notificatio_related_1106fe_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(
                fields=["user", "is_active"], name="notificatio_user_id_93f131_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="devicetoken",
            index=models.Index(fields=["token"], name="notificatio_token_b1ee3e_idx"),
        ),
    ]
