# Generated by Django 4.2.17 on 2026-03-11 10:44

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_date", models.DateField(db_index=True)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("online", "Online Booking"),
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone Booking"),
                            ("follow_up", "Follow-up"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for appointment / Chief complaint"
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, help_text="Symptoms described by patient"
                    ),
                ),
                (
                    "patient_notes",
                    models.TextField(blank=True, help_text="Notes from patient"),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, help_text="Notes from doctor (after consultation)"
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_by", models.CharField(blank=True, max_length=20)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "consultation_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to consultation.Consultation (set when consultation created)",
                        null=True,
                    ),
                ),
                (
                    "prescription_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to prescription if created",
                        null=True,
                    ),
                ),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_1h_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["-appointment_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("queue_number", models.PositiveIntegerField()),
                ("queue_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_wait_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated wait time in minutes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "appointment_queue",
                "ordering": ["queue_date", "queue_number"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("24h", "24 Hours Before"),
                            ("1h", "1 Hour Before"),
                            ("custom", "Custom Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "appointment_reminders",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                (
                    "slot_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Duration of each appointment slot in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "max_patients_per_slot",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum patients per time slot",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Consultation fee in INR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "doctor_schedules",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exception_date", models.DateField()),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("leave", "Leave/Holiday"),
                            ("modified", "Modified Hours"),
                            ("extra", "Extra Working Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "schedule_exceptions",
                "ordering": ["-exception_date"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("blocked", "Blocked"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("max_bookings", models.PositiveSmallIntegerField(default=1)),
                ("current_bookings", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "time_slots",
                "ordering": ["slot_date", "start_time"],
            },
        ),
    ]
