# Generated by Django 4.2.17 on 2026-01-26 15:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("appointment_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("rescheduled", "Rescheduled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "booking_type",
                    models.CharField(
                        choices=[
                            ("online", "Online Booking"),
                            ("walk_in", "Walk-in"),
                            ("phone", "Phone Booking"),
                            ("follow_up", "Follow-up"),
                        ],
                        default="online",
                        max_length=20,
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for appointment / Chief complaint"
                    ),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True, help_text="Symptoms described by patient"
                    ),
                ),
                (
                    "patient_notes",
                    models.TextField(blank=True, help_text="Notes from patient"),
                ),
                (
                    "doctor_notes",
                    models.TextField(
                        blank=True, help_text="Notes from doctor (after consultation)"
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True)),
                ("cancelled_by", models.CharField(blank=True, max_length=20)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "prescription_id",
                    models.UUIDField(
                        blank=True,
                        help_text="Reference to prescription if created",
                        null=True,
                    ),
                ),
                ("reminder_24h_sent", models.BooleanField(default=False)),
                ("reminder_1h_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rescheduled_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rescheduled_to",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "appointments",
                "ordering": ["-appointment_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("slot_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("booked", "Booked"),
                            ("blocked", "Blocked"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("max_bookings", models.PositiveSmallIntegerField(default=1)),
                ("current_bookings", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "time_slots",
                "ordering": ["slot_date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleException",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("exception_date", models.DateField()),
                (
                    "exception_type",
                    models.CharField(
                        choices=[
                            ("leave", "Leave/Holiday"),
                            ("modified", "Modified Hours"),
                            ("extra", "Extra Working Day"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_exceptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "schedule_exceptions",
                "ordering": ["-exception_date"],
            },
        ),
        migrations.CreateModel(
            name="DoctorSchedule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(6),
                        ],
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                (
                    "slot_duration_minutes",
                    models.PositiveSmallIntegerField(
                        default=30,
                        help_text="Duration of each appointment slot in minutes",
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                (
                    "max_patients_per_slot",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Maximum patients per time slot",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Consultation fee in INR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "doctor_schedules",
                "ordering": ["day_of_week", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("24h", "24 Hours Before"),
                            ("1h", "1 Hour Before"),
                            ("custom", "Custom Reminder"),
                        ],
                        max_length=20,
                    ),
                ),
                ("scheduled_time", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_reminders",
                "ordering": ["scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="AppointmentQueue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("queue_number", models.PositiveIntegerField()),
                ("queue_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("called", "Called"),
                            ("in_consultation", "In Consultation"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="waiting",
                        max_length=20,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(auto_now_add=True)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation_started_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_wait_minutes",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated wait time in minutes",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "appointment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="queue_entry",
                        to="appointments.appointment",
                    ),
                ),
            ],
            options={
                "db_table": "appointment_queue",
                "ordering": ["queue_date", "queue_number"],
            },
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="appointments.timeslot",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "slot_date", "status"],
                name="time_slots_doctor__947efb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["slot_date", "status"], name="time_slots_slot_da_204e3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "status"], name="time_slots_doctor__9efaeb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("doctor", "slot_date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="scheduleexception",
            index=models.Index(
                fields=["doctor", "exception_date"],
                name="schedule_ex_doctor__555f57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleexception",
            index=models.Index(
                fields=["exception_date", "exception_type"],
                name="schedule_ex_excepti_251f4e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduleexception",
            unique_together={("doctor", "exception_date")},
        ),
        migrations.AddIndex(
            model_name="doctorschedule",
            index=models.Index(
                fields=["doctor", "is_active"], name="doctor_sche_doctor__ec41b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorschedule",
            index=models.Index(
                fields=["day_of_week", "is_active"],
                name="doctor_sche_day_of__78dc3a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "day_of_week")},
        ),
        migrations.AddIndex(
            model_name="appointmentreminder",
            index=models.Index(
                fields=["status", "scheduled_time"],
                name="appointment_status_ade0b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentreminder",
            index=models.Index(
                fields=["appointment", "reminder_type"],
                name="appointment_appoint_ac378c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentqueue",
            index=models.Index(
                fields=["queue_date", "status"], name="appointment_queue_d_a41bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentqueue",
            index=models.Index(
                fields=["appointment", "status"], name="appointment_appoint_4198bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentqueue",
            index=models.Index(
                fields=["queue_date", "queue_number"],
                name="appointment_queue_d_ad2e82_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentqueue",
            unique_together={("appointment",)},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_6fe260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="appointment_doctor__45f502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "appointment_date"],
                name="appointment_doctor__4449b5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date"],
                name="appointment_patient_ee8848_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="appointment_status_06f84b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "start_time"],
                name="appointment_appoint_e54e0a_idx",
            ),
        ),
    ]
