# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="time_slots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduleexception",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedule_exceptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="doctorschedule",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointmentreminder",
            name="appointment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointmentqueue",
            name="appointment",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="queue_entry",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_appointments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="rescheduled_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rescheduled_to",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="time_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="appointments.timeslot",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "slot_date", "status"],
                name="time_slots_doctor__947efb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["slot_date", "status"], name="time_slots_slot_da_204e3d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="timeslot",
            index=models.Index(
                fields=["doctor", "status"], name="time_slots_doctor__9efaeb_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timeslot",
            unique_together={("doctor", "slot_date", "start_time")},
        ),
        migrations.AddIndex(
            model_name="scheduleexception",
            index=models.Index(
                fields=["doctor", "exception_date"],
                name="schedule_ex_doctor__555f57_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scheduleexception",
            index=models.Index(
                fields=["exception_date", "exception_type"],
                name="schedule_ex_excepti_251f4e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="scheduleexception",
            unique_together={("doctor", "exception_date")},
        ),
        migrations.AddIndex(
            model_name="doctorschedule",
            index=models.Index(
                fields=["doctor", "is_active"], name="doctor_sche_doctor__ec41b5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctorschedule",
            index=models.Index(
                fields=["day_of_week", "is_active"],
                name="doctor_sche_day_of__78dc3a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="doctorschedule",
            unique_together={("doctor", "day_of_week")},
        ),
        migrations.AddIndex(
            model_name="appointmentreminder",
            index=models.Index(
                fields=["status", "scheduled_time"],
                name="appointment_status_ade0b2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentreminder",
            index=models.Index(
                fields=["appointment", "reminder_type"],
                name="appointment_appoint_ac378c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentqueue",
            index=models.Index(
                fields=["queue_date", "status"], name="appointment_queue_d_a41bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentqueue",
            index=models.Index(
                fields=["appointment", "status"], name="appointment_appoint_4198bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointmentqueue",
            index=models.Index(
                fields=["queue_date", "queue_number"],
                name="appointment_queue_d_ad2e82_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointmentqueue",
            unique_together={("appointment",)},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "status"], name="appointment_patient_6fe260_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "status"], name="appointment_doctor__45f502_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["doctor", "appointment_date", "status"],
                name="appointment_doctor__889281_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "appointment_date", "status"],
                name="appointment_patient_cdefcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["status", "appointment_date"],
                name="appointment_status_06f84b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["appointment_date", "start_time"],
                name="appointment_appoint_e54e0a_idx",
            ),
        ),
    ]
