# Generated by Django 4.2.17 on 2026-01-24 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        help_text="Enter 10 digit Indian phone number",
                        max_length=15,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number (10 digits starting with 6-9)",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("doctor", "Doctor"),
                            ("patient", "Patient"),
                        ],
                        default="patient",
                        max_length=20,
                        verbose_name="Role",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Last Name"
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "profile_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profiles/%Y/%m/",
                        verbose_name="Profile Photo",
                    ),
                ),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("te", "Telugu"), ("hi", "Hindi"), ("en", "English")],
                        default="te",
                        max_length=5,
                        verbose_name="Preferred Language",
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Address")),
                (
                    "village",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Village/Town"
                    ),
                ),
                (
                    "mandal",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Mandal/Taluk"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="District"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        default="Andhra Pradesh", max_length=100, verbose_name="State"
                    ),
                ),
                (
                    "pincode",
                    models.CharField(blank=True, max_length=10, verbose_name="Pincode"),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(default=False, verbose_name="Phone Verified"),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(default=False, verbose_name="Email Verified"),
                ),
                (
                    "is_profile_complete",
                    models.BooleanField(default=False, verbose_name="Profile Complete"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "last_active",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Last Active"
                    ),
                ),
                (
                    "fcm_token",
                    models.CharField(
                        blank=True,
                        help_text="Firebase Cloud Messaging token for push notifications",
                        max_length=500,
                        verbose_name="FCM Token",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15, verbose_name="Phone")),
                ("otp", models.CharField(max_length=6, verbose_name="OTP")),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("registration", "Registration"),
                            ("login", "Login"),
                            ("password_reset", "Password Reset"),
                            ("phone_change", "Phone Change"),
                        ],
                        default="login",
                        max_length=20,
                        verbose_name="Purpose",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("max_attempts", models.PositiveIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "verbose_name": "OTP",
                "verbose_name_plural": "OTPs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("register", "Registration"),
                            ("profile_update", "Profile Update"),
                            ("password_change", "Password Change"),
                            ("appointment_book", "Appointment Booked"),
                            ("consultation", "Consultation"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                        verbose_name="Activity Type",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Activity",
                "verbose_name_plural": "User Activities",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PatientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=5,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "height_cm",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Height (cm)"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Weight (kg)",
                    ),
                ),
                (
                    "chronic_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of chronic conditions: ["diabetes", "hypertension"]',
                        verbose_name="Chronic Conditions",
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of allergies: ["penicillin", "peanuts"]',
                        verbose_name="Allergies",
                    ),
                ),
                (
                    "current_medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of current medications",
                        verbose_name="Current Medications",
                    ),
                ),
                (
                    "past_surgeries",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of past surgeries with dates",
                        verbose_name="Past Surgeries",
                    ),
                ),
                (
                    "family_history",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Family medical history",
                        verbose_name="Family Medical History",
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Emergency Contact Name",
                    ),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number (10 digits starting with 6-9)",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                        verbose_name="Emergency Contact Phone",
                    ),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Relation"
                    ),
                ),
                (
                    "has_insurance",
                    models.BooleanField(default=False, verbose_name="Has Insurance"),
                ),
                (
                    "insurance_provider",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Insurance Provider"
                    ),
                ),
                (
                    "insurance_id",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Insurance ID"
                    ),
                ),
                (
                    "is_literate",
                    models.BooleanField(
                        default=True,
                        help_text="Can the patient read and write?",
                        verbose_name="Is Literate",
                    ),
                ),
                (
                    "needs_voice_assistance",
                    models.BooleanField(
                        default=False,
                        help_text="Enable voice-based interaction",
                        verbose_name="Needs Voice Assistance",
                    ),
                ),
                (
                    "needs_large_text",
                    models.BooleanField(
                        default=False,
                        help_text="Enable larger text for better visibility",
                        verbose_name="Needs Large Text",
                    ),
                ),
                ("total_appointments", models.PositiveIntegerField(default=0)),
                ("total_consultations", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient Profile",
                "verbose_name_plural": "Patient Profiles",
            },
        ),
        migrations.CreateModel(
            name="DoctorProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Medical Council Registration Number",
                        max_length=50,
                        unique=True,
                        verbose_name="Medical Registration Number",
                    ),
                ),
                (
                    "registration_council",
                    models.CharField(
                        help_text="e.g., Andhra Pradesh Medical Council",
                        max_length=100,
                        verbose_name="Registration Council",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(
                        choices=[
                            ("general", "General Physician"),
                            ("pediatrics", "Pediatrics"),
                            ("gynecology", "Gynecology"),
                            ("orthopedics", "Orthopedics"),
                            ("dermatology", "Dermatology"),
                            ("ent", "ENT"),
                            ("ophthalmology", "Ophthalmology"),
                            ("cardiology", "Cardiology"),
                            ("neurology", "Neurology"),
                            ("psychiatry", "Psychiatry"),
                            ("dentistry", "Dentistry"),
                            ("ayurveda", "Ayurveda"),
                            ("homeopathy", "Homeopathy"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=50,
                        verbose_name="Specialization",
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        help_text="e.g., MBBS, MD, MS",
                        max_length=200,
                        verbose_name="Qualification",
                    ),
                ),
                (
                    "experience_years",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Years of Experience"
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Hospital/Clinic Name"
                    ),
                ),
                (
                    "hospital_address",
                    models.TextField(blank=True, verbose_name="Hospital Address"),
                ),
                (
                    "consultation_fee",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Fee for video consultation",
                        max_digits=10,
                        verbose_name="Consultation Fee (₹)",
                    ),
                ),
                (
                    "consultation_duration",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Consultation Duration (minutes)"
                    ),
                ),
                (
                    "languages_spoken",
                    models.JSONField(
                        default=list,
                        help_text='["telugu", "hindi", "english"]',
                        verbose_name="Languages Spoken",
                    ),
                ),
                (
                    "is_available_online",
                    models.BooleanField(
                        default=True, verbose_name="Available for Online Consultation"
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Verification Status",
                    ),
                ),
                (
                    "verification_document",
                    models.FileField(
                        blank=True,
                        help_text="Upload medical registration certificate",
                        null=True,
                        upload_to="doctor_docs/%Y/%m/",
                        verbose_name="Verification Document",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("total_consultations", models.PositiveIntegerField(default=0)),
                (
                    "bio",
                    models.TextField(
                        blank=True,
                        help_text="Brief description about the doctor",
                        verbose_name="About",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_doctors",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Profile",
                "verbose_name_plural": "Doctor Profiles",
            },
        ),
        migrations.CreateModel(
            name="AdminProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "admin_level",
                    models.CharField(
                        choices=[
                            ("super", "Super Admin"),
                            ("district", "District Admin"),
                            ("support", "Support Admin"),
                        ],
                        default="support",
                        max_length=20,
                        verbose_name="Admin Level",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Department"
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Designation"
                    ),
                ),
                ("can_manage_doctors", models.BooleanField(default=True)),
                ("can_manage_patients", models.BooleanField(default=True)),
                ("can_verify_doctors", models.BooleanField(default=False)),
                ("can_view_reports", models.BooleanField(default=True)),
                ("can_manage_content", models.BooleanField(default=False)),
                ("can_manage_admins", models.BooleanField(default=False)),
                ("can_access_system_settings", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Profile",
                "verbose_name_plural": "Admin Profiles",
            },
        ),
        migrations.CreateModel(
            name="FamilyHelper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "helper_name",
                    models.CharField(max_length=100, verbose_name="Helper Name"),
                ),
                (
                    "helper_phone",
                    models.CharField(
                        max_length=15,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid Indian phone number (10 digits starting with 6-9)",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                        verbose_name="Helper Phone",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("son", "Son"),
                            ("daughter", "Daughter"),
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("grandson", "Grandson"),
                            ("granddaughter", "Granddaughter"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                        verbose_name="Relationship",
                    ),
                ),
                ("can_book_appointments", models.BooleanField(default=True)),
                ("can_view_records", models.BooleanField(default=True)),
                ("can_chat_with_doctor", models.BooleanField(default=True)),
                ("can_manage_medications", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Primary helper receives all notifications",
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "helper_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="helping_patients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        limit_choices_to={"role": "patient"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Helper",
                "verbose_name_plural": "Family Helpers",
                "unique_together": {("patient", "helper_phone")},
            },
        ),
        migrations.CreateModel(
            name="DoctorLeave",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Leave Date")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Reason"),
                ),
                ("is_full_day", models.BooleanField(default=True)),
                ("start_time", models.TimeField(blank=True, null=True)),
                ("end_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaves",
                        to="users.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Leave",
                "verbose_name_plural": "Doctor Leaves",
                "ordering": ["date"],
                "unique_together": {("doctor", "date")},
            },
        ),
        migrations.CreateModel(
            name="DoctorAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                ("is_available", models.BooleanField(default=True)),
                (
                    "slot_duration",
                    models.PositiveIntegerField(
                        default=15, verbose_name="Slot Duration (minutes)"
                    ),
                ),
                (
                    "max_appointments",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum appointments for this slot",
                        verbose_name="Max Appointments",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="users.doctorprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor Availability",
                "verbose_name_plural": "Doctor Availabilities",
                "ordering": ["day_of_week", "start_time"],
                "unique_together": {("doctor", "day_of_week", "start_time")},
            },
        ),
    ]
