# Generated by Django 4.2.17 on 2026-02-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adminprofile",
            name="admin_level",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="can_access_system_settings",
        ),
        migrations.RemoveField(
            model_name="adminprofile",
            name="can_manage_admins",
        ),
        migrations.AlterField(
            model_name="adminprofile",
            name="can_manage_content",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="adminprofile",
            name="can_verify_doctors",
            field=models.BooleanField(default=True),
        ),
    ]
