# Generated by Django 4.2.17 on 2026-04-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="doctorleave",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="doctorleave",
            name="doctor",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="allergies",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="chronic_conditions",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="current_medications",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="emergency_contact_name",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="emergency_contact_phone",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="emergency_contact_relation",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="family_history",
        ),
        migrations.DeleteModel(
            name="DoctorAvailability",
        ),
        migrations.DeleteModel(
            name="DoctorLeave",
        ),
    ]
