# Generated by Django 4.2.17 on 2026-01-27 07:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnosis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("consultation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalCondition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("condition_name", models.CharField(max_length=200)),
                (
                    "condition_name_local",
                    models.CharField(
                        blank=True,
                        help_text="Condition name in local language",
                        max_length=200,
                    ),
                ),
                ("icd_code", models.CharField(blank=True, max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("managed", "Managed/Controlled"),
                            ("recurring", "Recurring"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                ("diagnosed_date", models.DateField(blank=True, null=True)),
                ("resolved_date", models.DateField(blank=True, null=True)),
                ("treatment_notes", models.TextField(blank=True)),
                ("is_chronic", models.BooleanField(default=False)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_conditions",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "diagnosed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="diagnosed_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diagnosis_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="medical_conditions",
                        to="diagnosis.diagnosissession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_conditions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Condition",
                "verbose_name_plural": "Medical Conditions",
                "db_table": "health_records_condition",
                "ordering": ["-diagnosed_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicalDocument",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Prescription"),
                            ("lab_report", "Lab Report"),
                            ("xray", "X-Ray"),
                            ("mri", "MRI Scan"),
                            ("ct_scan", "CT Scan"),
                            ("ultrasound", "Ultrasound"),
                            ("ecg", "ECG/EKG"),
                            ("blood_report", "Blood Test Report"),
                            ("urine_report", "Urine Test Report"),
                            ("discharge_summary", "Discharge Summary"),
                            ("medical_certificate", "Medical Certificate"),
                            ("insurance", "Insurance Document"),
                            ("vaccination", "Vaccination Certificate"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="health_records/documents/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        default=0, help_text="File size in bytes"
                    ),
                ),
                ("file_type", models.CharField(blank=True, max_length=50)),
                (
                    "document_date",
                    models.DateField(
                        blank=True, help_text="Date on the document", null=True
                    ),
                ),
                ("hospital_name", models.CharField(blank=True, max_length=200)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                (
                    "is_shared_with_doctors",
                    models.BooleanField(
                        default=True, help_text="Allow doctors to view this document"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="health_documents",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "medical_condition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="health_records.medicalcondition",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Medical Document",
                "verbose_name_plural": "Medical Documents",
                "db_table": "health_records_document",
                "ordering": ["-document_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VitalSign",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "systolic_bp",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Systolic blood pressure (mmHg)",
                        null=True,
                    ),
                ),
                (
                    "diastolic_bp",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Diastolic blood pressure (mmHg)",
                        null=True,
                    ),
                ),
                (
                    "heart_rate",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Heart rate (bpm)", null=True
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Body temperature (°F)",
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "respiratory_rate",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Breaths per minute", null=True
                    ),
                ),
                (
                    "oxygen_saturation",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="SpO2 (%)", null=True
                    ),
                ),
                (
                    "blood_sugar",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Blood glucose (mg/dL)", null=True
                    ),
                ),
                (
                    "blood_sugar_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fasting", "Fasting"),
                            ("pp", "Post Prandial"),
                            ("random", "Random"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("self", "Self Recorded"),
                            ("clinic", "Clinic/Hospital"),
                            ("home_device", "Home Device"),
                            ("consultation", "During Consultation"),
                        ],
                        default="self",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vital_signs",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_vitals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vital_signs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vital Sign",
                "verbose_name_plural": "Vital Signs",
                "db_table": "health_records_vital_sign",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("vaccine_name", models.CharField(max_length=200)),
                ("vaccine_name_local", models.CharField(blank=True, max_length=200)),
                (
                    "vaccine_type",
                    models.CharField(
                        choices=[
                            ("covid", "COVID-19"),
                            ("flu", "Influenza"),
                            ("hepatitis_a", "Hepatitis A"),
                            ("hepatitis_b", "Hepatitis B"),
                            ("typhoid", "Typhoid"),
                            ("tetanus", "Tetanus"),
                            ("rabies", "Rabies"),
                            ("polio", "Polio"),
                            ("mmr", "MMR"),
                            ("bcg", "BCG"),
                            ("dpt", "DPT"),
                            ("chickenpox", "Chickenpox"),
                            ("hpv", "HPV"),
                            ("pneumonia", "Pneumonia"),
                            ("meningitis", "Meningitis"),
                            ("yellow_fever", "Yellow Fever"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "dose_number",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Dose number (1, 2, 3, etc.)"
                    ),
                ),
                (
                    "total_doses",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Total doses required"
                    ),
                ),
                ("vaccination_date", models.DateField()),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("administered_by", models.CharField(blank=True, max_length=200)),
                (
                    "administered_at",
                    models.CharField(
                        blank=True, help_text="Hospital/Clinic name", max_length=200
                    ),
                ),
                ("batch_number", models.CharField(blank=True, max_length=100)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("side_effects", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                (
                    "certificate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccination_record",
                        to="health_records.medicaldocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_vaccinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination Record",
                "verbose_name_plural": "Vaccination Records",
                "db_table": "health_records_vaccination",
                "ordering": ["-vaccination_date"],
            },
        ),
        migrations.CreateModel(
            name="LabReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("report_name", models.CharField(max_length=200)),
                (
                    "lab_type",
                    models.CharField(
                        choices=[
                            ("blood", "Blood Test"),
                            ("urine", "Urine Test"),
                            ("stool", "Stool Test"),
                            ("thyroid", "Thyroid Panel"),
                            ("lipid", "Lipid Profile"),
                            ("liver", "Liver Function"),
                            ("kidney", "Kidney Function"),
                            ("diabetes", "Diabetes Panel"),
                            ("vitamin", "Vitamin Panel"),
                            ("hormone", "Hormone Panel"),
                            ("allergy", "Allergy Test"),
                            ("infection", "Infection Panel"),
                            ("other", "Other"),
                        ],
                        default="blood",
                        max_length=20,
                    ),
                ),
                ("test_date", models.DateField()),
                ("lab_name", models.CharField(blank=True, max_length=200)),
                ("doctor_name", models.CharField(blank=True, max_length=200)),
                (
                    "results",
                    models.JSONField(default=list, help_text="List of test results"),
                ),
                (
                    "overall_status",
                    models.CharField(
                        choices=[
                            ("normal", "All Normal"),
                            ("abnormal", "Some Abnormal"),
                            ("critical", "Critical Values"),
                            ("pending", "Pending Review"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("interpretation", models.TextField(blank=True)),
                ("recommendations", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_reports",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "document",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_report_data",
                        to="health_records.medicaldocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lab Report",
                "verbose_name_plural": "Lab Reports",
                "db_table": "health_records_lab_report",
                "ordering": ["-test_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Hospitalization",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("hospital_name", models.CharField(max_length=200)),
                ("hospital_address", models.TextField(blank=True)),
                ("admission_date", models.DateField()),
                ("discharge_date", models.DateField(blank=True, null=True)),
                (
                    "admission_type",
                    models.CharField(
                        choices=[
                            ("emergency", "Emergency"),
                            ("planned", "Planned/Scheduled"),
                            ("transfer", "Transfer"),
                        ],
                        default="emergency",
                        max_length=20,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason for admission")),
                ("diagnosis", models.TextField(blank=True)),
                ("treating_doctor", models.CharField(blank=True, max_length=200)),
                ("department", models.CharField(blank=True, max_length=100)),
                (
                    "procedures",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of procedures performed",
                    ),
                ),
                ("discharge_summary", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("follow_up_notes", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalizations",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "discharge_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hospitalization",
                        to="health_records.medicaldocument",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hospitalizations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospitalization",
                "verbose_name_plural": "Hospitalizations",
                "db_table": "health_records_hospitalization",
                "ordering": ["-admission_date"],
            },
        ),
        migrations.CreateModel(
            name="HealthProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A Positive"),
                            ("A-", "A Negative"),
                            ("B+", "B Positive"),
                            ("B-", "B Negative"),
                            ("AB+", "AB Positive"),
                            ("AB-", "AB Negative"),
                            ("O+", "O Positive"),
                            ("O-", "O Negative"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Height in centimeters",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Weight in kilograms",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "allergies",
                    models.JSONField(
                        blank=True, default=list, help_text="List of allergies"
                    ),
                ),
                (
                    "chronic_conditions",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of chronic conditions like diabetes, hypertension",
                    ),
                ),
                (
                    "current_medications",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of current medications",
                    ),
                ),
                (
                    "family_history",
                    models.JSONField(
                        blank=True, default=dict, help_text="Family medical history"
                    ),
                ),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("former", "Former Smoker"),
                            ("current", "Current Smoker"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "alcohol_consumption",
                    models.CharField(
                        choices=[
                            ("never", "Never"),
                            ("occasional", "Occasional"),
                            ("regular", "Regular"),
                            ("former", "Former"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=50),
                ),
                (
                    "notes",
                    models.TextField(blank=True, help_text="Additional health notes"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Profile",
                "verbose_name_plural": "Health Profiles",
                "db_table": "health_records_profile",
            },
        ),
        migrations.CreateModel(
            name="FamilyMedicalHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "relation",
                    models.CharField(
                        choices=[
                            ("father", "Father"),
                            ("mother", "Mother"),
                            ("brother", "Brother"),
                            ("sister", "Sister"),
                            ("grandfather_paternal", "Grandfather (Paternal)"),
                            ("grandmother_paternal", "Grandmother (Paternal)"),
                            ("grandfather_maternal", "Grandfather (Maternal)"),
                            ("grandmother_maternal", "Grandmother (Maternal)"),
                            ("uncle", "Uncle"),
                            ("aunt", "Aunt"),
                            ("child", "Child"),
                            ("spouse", "Spouse"),
                            ("other", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "relation_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the relative (optional)",
                        max_length=100,
                    ),
                ),
                ("condition", models.CharField(max_length=200)),
                ("condition_local", models.CharField(blank=True, max_length=200)),
                (
                    "age_at_diagnosis",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Age when condition was diagnosed",
                        null=True,
                    ),
                ),
                ("is_deceased", models.BooleanField(default=False)),
                (
                    "age_at_death",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cause_of_death", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="family_medical_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Family Medical History",
                "verbose_name_plural": "Family Medical Histories",
                "db_table": "health_records_family_history",
                "ordering": ["relation", "condition"],
            },
        ),
        migrations.CreateModel(
            name="Allergy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("allergen", models.CharField(max_length=200)),
                ("allergen_local", models.CharField(blank=True, max_length=200)),
                (
                    "allergy_type",
                    models.CharField(
                        choices=[
                            ("drug", "Drug/Medication"),
                            ("food", "Food"),
                            ("environmental", "Environmental"),
                            ("insect", "Insect"),
                            ("latex", "Latex"),
                            ("animal", "Animal"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("life_threatening", "Life Threatening"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "reaction",
                    models.TextField(help_text="Description of allergic reaction"),
                ),
                ("first_observed", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive/Outgrown"),
                            ("suspected", "Suspected"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("diagnosed_by", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allergy_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Allergy",
                "verbose_name_plural": "Allergies",
                "db_table": "health_records_allergy",
                "ordering": ["-severity", "allergen"],
            },
        ),
        migrations.CreateModel(
            name="SharedRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "share_type",
                    models.CharField(
                        choices=[
                            ("all", "All Records"),
                            ("profile", "Health Profile Only"),
                            ("documents", "Specific Documents"),
                            ("conditions", "Medical Conditions"),
                            ("lab_reports", "Lab Reports"),
                            ("vaccinations", "Vaccination Records"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("is_permanent", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("access_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shared_records",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_shared_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_with",
                        to="health_records.medicaldocument",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Record",
                "verbose_name_plural": "Shared Records",
                "db_table": "health_records_shared",
                "ordering": ["-created_at"],
                "unique_together": {
                    ("patient", "doctor", "share_type", "consultation")
                },
            },
        ),
    ]
