# Generated by Django 4.2.17 on 2026-02-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("health_records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicaldocument",
            name="file",
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="file_path",
            field=models.CharField(
                blank=True, help_text="Path to file in Supabase Storage", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="original_filename",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="medicaldocument",
            name="storage_type",
            field=models.CharField(
                choices=[("local", "Local Storage"), ("supabase", "Supabase Storage")],
                default="supabase",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="medicaldocument",
            name="file_type",
            field=models.CharField(
                blank=True, help_text="File extension", max_length=20
            ),
        ),
    ]
