# Generated by Django 4.2.17 on 2026-04-10 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "consultation",
            "0003_consultationnote_consultatio_consult_680a65_idx_and_more",
        ),
        ("health_records", "0003_alter_allergy_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalcondition",
            name="consultation_id",
        ),
        migrations.AddField(
            model_name="medicalcondition",
            name="consultation",
            field=models.ForeignKey(
                blank=True,
                help_text="Consultation during which this condition was diagnosed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_conditions_diagnosed",
                to="consultation.consultation",
            ),
        ),
        migrations.AddIndex(
            model_name="labreport",
            index=models.Index(
                fields=["user", "test_date"], name="health_reco_user_id_ed3882_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labreport",
            index=models.Index(
                fields=["user", "overall_status"], name="health_reco_user_id_2f3e6a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["user", "document_type", "created_at"],
                name="health_reco_user_id_e51afd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicaldocument",
            index=models.Index(
                fields=["user", "document_date"], name="health_reco_user_id_f0b0d4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["user", "vaccination_date"],
                name="health_reco_user_id_9c4bff_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["user", "next_due_date"], name="health_reco_user_id_463384_idx"
            ),
        ),
    ]
