"""
Management command to load sample emergency services (hospitals, ambulances).

Usage:
    python manage.py load_emergency_services
    python manage.py load_emergency_services --clear
"""

from django.core.management.base import BaseCommand
from django.db import transaction

from apps.emergency.models import EmergencyService


# Sample emergency services data (Andhra Pradesh & Telangana)
SERVICES_DATA = [
    # ==========================================================================
    # HOSPITALS - HYDERABAD
    # ==========================================================================
    {
        'name': 'Gandhi Hospital',
        'name_local': 'గాంధీ ఆసుపత్రి',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '04023305424',
        'phone_emergency': '108',
        'address': 'Musheerabad, Secunderabad',
        'address_local': 'ముషీరాబాద్, సికింద్రాబాద్',
        'landmark': 'Near Musheerabad Bus Stand',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500003',
        'latitude': 17.4010,
        'longitude': 78.4747,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 1600,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'Osmania General Hospital',
        'name_local': 'ఉస్మానియా జనరల్ ఆసుపత్రి',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '04024600146',
        'phone_emergency': '108',
        'address': 'Afzal Gunj, Hyderabad',
        'address_local': 'అఫ్జల్ గంజ్, హైదరాబాద్',
        'landmark': 'Near High Court',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500012',
        'latitude': 17.3712,
        'longitude': 78.4747,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 1168,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'NIMS Hospital',
        'name_local': 'నిమ్స్ ఆసుపత్రి',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '04023390933',
        'phone_emergency': '04023390933',
        'address': 'Punjagutta, Hyderabad',
        'address_local': 'పంజగుట్ట, హైదరాబాద్',
        'landmark': 'Near Punjagutta Metro Station',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500082',
        'latitude': 17.4340,
        'longitude': 78.4480,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 1500,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'Apollo Hospitals Jubilee Hills',
        'name_local': 'అపోలో ఆసుపత్రి జూబ్లీ హిల్స్',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '04023607777',
        'phone_emergency': '04023607777',
        'address': 'Jubilee Hills, Hyderabad',
        'address_local': 'జూబ్లీ హిల్స్, హైదరాబాద్',
        'landmark': 'Road No. 72, Jubilee Hills',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500033',
        'latitude': 17.4269,
        'longitude': 78.4099,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 550,
        'is_government': False,
        'is_verified': True,
    },
    {
        'name': 'Care Hospitals Banjara Hills',
        'name_local': 'కేర్ ఆసుపత్రి బంజారా హిల్స్',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '04030418888',
        'phone_emergency': '04030418888',
        'address': 'Road No. 1, Banjara Hills, Hyderabad',
        'address_local': 'రోడ్ నం. 1, బంజారా హిల్స్',
        'landmark': 'Near GVK One Mall',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500034',
        'latitude': 17.4156,
        'longitude': 78.4487,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 435,
        'is_government': False,
        'is_verified': True,
    },
    # ==========================================================================
    # HOSPITALS - VIJAYAWADA
    # ==========================================================================
    {
        'name': 'Government General Hospital Vijayawada',
        'name_local': 'ప్రభుత్వ జనరల్ ఆసుపత్రి విజయవాడ',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '08662577100',
        'phone_emergency': '108',
        'address': 'Nehru Nagar, Vijayawada',
        'address_local': 'నెహ్రూ నగర్, విజయవాడ',
        'landmark': 'Near Vijayawada Railway Station',
        'district': 'Krishna',
        'state': 'Andhra Pradesh',
        'pincode': '520002',
        'latitude': 16.5180,
        'longitude': 80.6400,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 1000,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'Manipal Hospital Vijayawada',
        'name_local': 'మణిపాల్ ఆసుపత్రి విజయవాడ',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '08662969999',
        'phone_emergency': '08662969999',
        'address': 'Tadepalli, Vijayawada',
        'address_local': 'తాడేపల్లి, విజయవాడ',
        'landmark': 'NH-65, Tadepalli',
        'district': 'Guntur',
        'state': 'Andhra Pradesh',
        'pincode': '522501',
        'latitude': 16.4831,
        'longitude': 80.5996,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 300,
        'is_government': False,
        'is_verified': True,
    },
    # ==========================================================================
    # HOSPITALS - VISAKHAPATNAM
    # ==========================================================================
    {
        'name': 'King George Hospital',
        'name_local': 'కింగ్ జార్జ్ ఆసుపత్రి',
        'service_type': 'hospital',
        'facility_level': 'tertiary',
        'phone_primary': '08912564891',
        'phone_emergency': '108',
        'address': 'Maharani Peta, Visakhapatnam',
        'address_local': 'మహారాణి పేట, విశాఖపట్నం',
        'landmark': 'Near Railway Station',
        'district': 'Visakhapatnam',
        'state': 'Andhra Pradesh',
        'pincode': '530002',
        'latitude': 17.7050,
        'longitude': 83.2969,
        'is_24x7': True,
        'has_emergency_ward': True,
        'has_icu': True,
        'has_ambulance': True,
        'has_blood_bank': True,
        'bed_count': 1500,
        'is_government': True,
        'is_verified': True,
    },
    # ==========================================================================
    # PRIMARY HEALTH CENTERS
    # ==========================================================================
    {
        'name': 'PHC Kondapur',
        'name_local': 'ప్రాథమిక ఆరోగ్య కేంద్రం కొండాపూర్',
        'service_type': 'phc',
        'facility_level': 'primary',
        'phone_primary': '04023019876',
        'phone_emergency': '108',
        'address': 'Kondapur Village, Serilingampally',
        'address_local': 'కొండాపూర్ గ్రామం',
        'landmark': 'Near Kondapur Bus Stop',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500084',
        'latitude': 17.4605,
        'longitude': 78.3520,
        'is_24x7': False,
        'opening_time': '09:00:00',
        'closing_time': '17:00:00',
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 10,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'PHC Gachibowli',
        'name_local': 'ప్రాథమిక ఆరోగ్య కేంద్రం గచ్చిబౌలి',
        'service_type': 'phc',
        'facility_level': 'primary',
        'phone_primary': '04023000123',
        'phone_emergency': '108',
        'address': 'Gachibowli Village',
        'address_local': 'గచ్చిబౌలి గ్రామం',
        'landmark': 'Near Gachibowli Stadium',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500032',
        'latitude': 17.4401,
        'longitude': 78.3489,
        'is_24x7': False,
        'opening_time': '09:00:00',
        'closing_time': '17:00:00',
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 10,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'PHC Patancheru',
        'name_local': 'ప్రాథమిక ఆరోగ్య కేంద్రం పటాన్‌చెరు',
        'service_type': 'phc',
        'facility_level': 'primary',
        'phone_primary': '08455245678',
        'phone_emergency': '108',
        'address': 'Patancheru Town',
        'address_local': 'పటాన్‌చెరు పట్టణం',
        'landmark': 'Near Patancheru Bus Stand',
        'district': 'Sangareddy',
        'state': 'Telangana',
        'pincode': '502319',
        'latitude': 17.5326,
        'longitude': 78.2648,
        'is_24x7': False,
        'opening_time': '09:00:00',
        'closing_time': '17:00:00',
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 15,
        'is_government': True,
        'is_verified': True,
    },
    # ==========================================================================
    # AMBULANCE SERVICES
    # ==========================================================================
    {
        'name': '108 EMRI Ambulance - Hyderabad',
        'name_local': '108 EMRI అంబులెన్స్ - హైదరాబాద్',
        'service_type': 'ambulance',
        'facility_level': 'specialized',
        'phone_primary': '108',
        'phone_emergency': '108',
        'address': 'Hyderabad Control Room',
        'address_local': 'హైదరాబాద్ కంట్రోల్ రూమ్',
        'landmark': 'Serves all of Hyderabad',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500001',
        'latitude': 17.3850,
        'longitude': 78.4867,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': True,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': '108 EMRI Ambulance - Vijayawada',
        'name_local': '108 EMRI అంబులెన్స్ - విజయవాడ',
        'service_type': 'ambulance',
        'facility_level': 'specialized',
        'phone_primary': '108',
        'phone_emergency': '108',
        'address': 'Vijayawada Control Room',
        'address_local': 'విజయవాడ కంట్రోల్ రూమ్',
        'landmark': 'Serves Krishna District',
        'district': 'Krishna',
        'state': 'Andhra Pradesh',
        'pincode': '520001',
        'latitude': 16.5062,
        'longitude': 80.6480,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': True,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': '108 EMRI Ambulance - Visakhapatnam',
        'name_local': '108 EMRI అంబులెన్స్ - విశాఖపట్నం',
        'service_type': 'ambulance',
        'facility_level': 'specialized',
        'phone_primary': '108',
        'phone_emergency': '108',
        'address': 'Visakhapatnam Control Room',
        'address_local': 'విశాఖపట్నం కంట్రోల్ రూమ్',
        'landmark': 'Serves Visakhapatnam District',
        'district': 'Visakhapatnam',
        'state': 'Andhra Pradesh',
        'pincode': '530001',
        'latitude': 17.6868,
        'longitude': 83.2185,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': True,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
    # ==========================================================================
    # BLOOD BANKS
    # ==========================================================================
    {
        'name': 'Red Cross Blood Bank Hyderabad',
        'name_local': 'రెడ్ క్రాస్ బ్లడ్ బ్యాంక్ హైదరాబాద్',
        'service_type': 'blood_bank',
        'facility_level': 'specialized',
        'phone_primary': '04024732220',
        'phone_emergency': '04024732220',
        'address': 'Red Cross Bhavan, Nampally',
        'address_local': 'రెడ్ క్రాస్ భవన్, నాంపల్లి',
        'landmark': 'Near Nampally Railway Station',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500001',
        'latitude': 17.3784,
        'longitude': 78.4725,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': True,
        'bed_count': 0,
        'is_government': False,
        'is_verified': True,
    },
    {
        'name': 'Thalassemia Sickle Cell Society Blood Bank',
        'name_local': 'థలసేమియా సికిల్ సెల్ సొసైటీ బ్లడ్ బ్యాంక్',
        'service_type': 'blood_bank',
        'facility_level': 'specialized',
        'phone_primary': '04027150677',
        'phone_emergency': '04027150677',
        'address': 'Somajiguda, Hyderabad',
        'address_local': 'సోమాజిగూడ, హైదరాబాద్',
        'landmark': 'Near Raj Bhavan',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500082',
        'latitude': 17.4244,
        'longitude': 78.4527,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': True,
        'bed_count': 0,
        'is_government': False,
        'is_verified': True,
    },
    # ==========================================================================
    # 24x7 PHARMACIES
    # ==========================================================================
    {
        'name': 'Apollo Pharmacy - Jubilee Hills',
        'name_local': 'అపోలో ఫార్మసీ - జూబ్లీ హిల్స్',
        'service_type': 'pharmacy',
        'facility_level': 'primary',
        'phone_primary': '18001020244',
        'phone_emergency': '18001020244',
        'address': 'Road No. 36, Jubilee Hills',
        'address_local': 'రోడ్ నం. 36, జూబ్లీ హిల్స్',
        'landmark': 'Near Peddamma Temple',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500033',
        'latitude': 17.4312,
        'longitude': 78.4079,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': False,
        'is_verified': True,
    },
    {
        'name': 'MedPlus 24 Hour - Banjara Hills',
        'name_local': 'మెడ్‌ప్లస్ 24 గంటలు - బంజారా హిల్స్',
        'service_type': 'pharmacy',
        'facility_level': 'primary',
        'phone_primary': '04040101010',
        'phone_emergency': '04040101010',
        'address': 'Road No. 12, Banjara Hills',
        'address_local': 'రోడ్ నం. 12, బంజారా హిల్స్',
        'landmark': 'Near KBR Park',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500034',
        'latitude': 17.4156,
        'longitude': 78.4347,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': False,
        'is_verified': True,
    },
    # ==========================================================================
    # POLICE STATIONS (for emergencies)
    # ==========================================================================
    {
        'name': 'Banjara Hills Police Station',
        'name_local': 'బంజారా హిల్స్ పోలీస్ స్టేషన్',
        'service_type': 'police',
        'facility_level': 'primary',
        'phone_primary': '04027855276',
        'phone_emergency': '100',
        'address': 'Road No. 12, Banjara Hills',
        'address_local': 'రోడ్ నం. 12, బంజారా హిల్స్',
        'landmark': 'Near KBR Park',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500034',
        'latitude': 17.4178,
        'longitude': 78.4347,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'Jubilee Hills Police Station',
        'name_local': 'జూబ్లీ హిల్స్ పోలీస్ స్టేషన్',
        'service_type': 'police',
        'facility_level': 'primary',
        'phone_primary': '04023542546',
        'phone_emergency': '100',
        'address': 'Road No. 45, Jubilee Hills',
        'address_local': 'రోడ్ నం. 45, జూబ్లీ హిల్స్',
        'landmark': 'Near Jubilee Hills Check Post',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500033',
        'latitude': 17.4350,
        'longitude': 78.4079,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
    # ==========================================================================
    # FIRE STATIONS
    # ==========================================================================
    {
        'name': 'Fire Station Secunderabad',
        'name_local': 'ఫైర్ స్టేషన్ సికింద్రాబాద్',
        'service_type': 'fire',
        'facility_level': 'primary',
        'phone_primary': '04027803333',
        'phone_emergency': '101',
        'address': 'Paradise Circle, Secunderabad',
        'address_local': 'పారడైజ్ సర్కిల్, సికింద్రాబాద్',
        'landmark': 'Near Paradise Hotel',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500003',
        'latitude': 17.4425,
        'longitude': 78.4811,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
    {
        'name': 'Fire Station Abids',
        'name_local': 'ఫైర్ స్టేషన్ ఆబిడ్స్',
        'service_type': 'fire',
        'facility_level': 'primary',
        'phone_primary': '04024756666',
        'phone_emergency': '101',
        'address': 'Abids, Hyderabad',
        'address_local': 'ఆబిడ్స్, హైదరాబాద్',
        'landmark': 'Near GPO',
        'district': 'Hyderabad',
        'state': 'Telangana',
        'pincode': '500001',
        'latitude': 17.3893,
        'longitude': 78.4722,
        'is_24x7': True,
        'has_emergency_ward': False,
        'has_icu': False,
        'has_ambulance': False,
        'has_blood_bank': False,
        'bed_count': 0,
        'is_government': True,
        'is_verified': True,
    },
]


class Command(BaseCommand):
    help = 'Load sample emergency services (hospitals, ambulances, etc.)'

    def add_arguments(self, parser):
        parser.add_argument(
            '--clear',
            action='store_true',
            help='Clear existing services before loading',
        )

    def handle(self, *args, **options):
        if options.get('clear'):
            self.stdout.write('Clearing existing emergency services...')
            EmergencyService.objects.all().delete()
        
        created_count = 0
        updated_count = 0
        
        with transaction.atomic():
            for data in SERVICES_DATA:
                # Handle time fields
                opening_time = data.pop('opening_time', None)
                closing_time = data.pop('closing_time', None)
                
                service, created = EmergencyService.objects.update_or_create(
                    name=data['name'],
                    district=data['district'],
                    defaults={
                        **data,
                        'opening_time': opening_time,
                        'closing_time': closing_time,
                    }
                )
                
                if created:
                    created_count += 1
                else:
                    updated_count += 1
        
        # Summary by type
        summary = {}
        for service_type, display_name in EmergencyService.SERVICE_TYPES:
            count = EmergencyService.objects.filter(service_type=service_type).count()
            if count > 0:
                summary[display_name] = count
        
        self.stdout.write(
            self.style.SUCCESS(
                f'✓ Emergency Services: {created_count} created, {updated_count} updated'
            )
        )
        
        for service_type, count in summary.items():
            self.stdout.write(f'  - {service_type}: {count}')