# Generated by Django 4.2.17 on 2026-03-11 10:44

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DrugInteraction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("contraindicated", "Contraindicated"),
                        ],
                        default="moderate",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of the interaction"),
                ),
                (
                    "description_local",
                    models.TextField(
                        blank=True, help_text="Description in local language"
                    ),
                ),
                (
                    "effect",
                    models.TextField(
                        blank=True, help_text="What happens when taken together"
                    ),
                ),
                (
                    "recommendation",
                    models.TextField(
                        blank=True, help_text="What to do if interaction occurs"
                    ),
                ),
                ("recommendation_local", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "drug_interactions",
                "ordering": ["-severity"],
            },
        ),
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                (
                    "name_generic",
                    models.CharField(
                        db_index=True, help_text="Generic/salt name", max_length=255
                    ),
                ),
                (
                    "name_local",
                    models.CharField(
                        blank=True,
                        help_text="Name in local language (Telugu/Hindi)",
                        max_length=255,
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("manufacturer", models.CharField(blank=True, max_length=255)),
                (
                    "medicine_type",
                    models.CharField(
                        choices=[
                            ("tablet", "Tablet"),
                            ("capsule", "Capsule"),
                            ("syrup", "Syrup"),
                            ("injection", "Injection"),
                            ("drops", "Drops"),
                            ("cream", "Cream/Ointment"),
                            ("gel", "Gel"),
                            ("powder", "Powder"),
                            ("inhaler", "Inhaler"),
                            ("spray", "Spray"),
                            ("patch", "Patch"),
                            ("suppository", "Suppository"),
                            ("suspension", "Suspension"),
                            ("solution", "Solution"),
                            ("other", "Other"),
                        ],
                        default="tablet",
                        max_length=20,
                    ),
                ),
                (
                    "strength",
                    models.CharField(
                        blank=True, help_text="e.g., 500mg, 10ml", max_length=100
                    ),
                ),
                (
                    "pack_size",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 10 tablets, 100ml bottle",
                        max_length=100,
                    ),
                ),
                (
                    "prescription_type",
                    models.CharField(
                        choices=[
                            ("otc", "Over The Counter"),
                            ("prescription", "Prescription Required"),
                            ("controlled", "Controlled Substance"),
                        ],
                        default="prescription",
                        max_length=20,
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum Retail Price in INR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "composition",
                    models.TextField(
                        blank=True, help_text="Active ingredients and their quantities"
                    ),
                ),
                (
                    "uses",
                    models.TextField(
                        blank=True, help_text="What the medicine is used for"
                    ),
                ),
                (
                    "uses_local",
                    models.TextField(blank=True, help_text="Uses in local language"),
                ),
                (
                    "dosage_info",
                    models.TextField(
                        blank=True, help_text="General dosage instructions"
                    ),
                ),
                (
                    "dosage_info_local",
                    models.TextField(blank=True, help_text="Dosage in local language"),
                ),
                (
                    "side_effects",
                    models.TextField(blank=True, help_text="Common side effects"),
                ),
                (
                    "side_effects_local",
                    models.TextField(
                        blank=True, help_text="Side effects in local language"
                    ),
                ),
                (
                    "warnings",
                    models.TextField(
                        blank=True, help_text="Important warnings and precautions"
                    ),
                ),
                (
                    "warnings_local",
                    models.TextField(
                        blank=True, help_text="Warnings in local language"
                    ),
                ),
                (
                    "contraindications",
                    models.TextField(
                        blank=True, help_text="When NOT to use this medicine"
                    ),
                ),
                (
                    "storage_info",
                    models.CharField(
                        blank=True,
                        default="Store in a cool, dry place away from sunlight",
                        max_length=255,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="e.g., Antibiotic, Painkiller, Antacid",
                        max_length=100,
                    ),
                ),
                ("subcategory", models.CharField(blank=True, max_length=100)),
                (
                    "is_generic",
                    models.BooleanField(
                        default=False, help_text="Is this a generic medicine?"
                    ),
                ),
                ("is_habit_forming", models.BooleanField(default=False)),
                ("requires_refrigeration", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "medicines",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MedicineAlternative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "similarity_score",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="100 = exact same composition",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "price_difference_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Negative = cheaper alternative",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Any notes about the alternative"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "medicine_alternatives",
                "ordering": ["-similarity_score", "price_difference_percent"],
            },
        ),
        migrations.CreateModel(
            name="MedicineReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("medicine_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                (
                    "reminder_times",
                    models.JSONField(
                        default=list,
                        help_text='List of times ["08:00", "14:00", "20:00"]',
                    ),
                ),
                (
                    "days_of_week",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="[0,1,2,3,4,5,6] where 0=Monday",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text='e.g., "Take after food", "With warm water"',
                    ),
                ),
                ("instructions_local", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "notify_before_minutes",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Send reminder X minutes before scheduled time",
                    ),
                ),
                (
                    "notify_family_helper",
                    models.BooleanField(
                        default=False, help_text="Also notify family helper"
                    ),
                ),
                ("allow_snooze", models.BooleanField(default=True)),
                ("snooze_minutes", models.PositiveSmallIntegerField(default=10)),
                ("max_snoozes", models.PositiveSmallIntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "medicine_reminders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MedicineSearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("search_query", models.CharField(max_length=255)),
                ("results_count", models.PositiveIntegerField(default=0)),
                ("searched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "medicine_search_history",
                "ordering": ["-searched_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionMedicine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(
                        help_text="Medicine name (if not in database)", max_length=255
                    ),
                ),
                (
                    "dosage",
                    models.CharField(
                        help_text='e.g., "1 tablet", "5ml", "2 drops"', max_length=100
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once_daily", "Once Daily"),
                            ("twice_daily", "Twice Daily"),
                            ("thrice_daily", "Three Times Daily"),
                            ("four_times", "Four Times Daily"),
                            ("every_4_hours", "Every 4 Hours"),
                            ("every_6_hours", "Every 6 Hours"),
                            ("every_8_hours", "Every 8 Hours"),
                            ("every_12_hours", "Every 12 Hours"),
                            ("weekly", "Once a Week"),
                            ("as_needed", "As Needed (SOS)"),
                            ("custom", "Custom Schedule"),
                        ],
                        default="once_daily",
                        max_length=20,
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("before_food", "Before Food"),
                            ("after_food", "After Food"),
                            ("with_food", "With Food"),
                            ("empty_stomach", "Empty Stomach"),
                            ("bedtime", "At Bedtime"),
                            ("morning", "Morning"),
                            ("any_time", "Any Time"),
                        ],
                        default="after_food",
                        max_length=20,
                    ),
                ),
                (
                    "custom_times",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of times like ["08:00", "14:00", "20:00"]',
                    ),
                ),
                (
                    "duration_days",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of days to take", null=True
                    ),
                ),
                ("start_date", models.DateField(default=django.utils.timezone.now)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "special_instructions",
                    models.TextField(blank=True, help_text="Any special instructions"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "quantity_prescribed",
                    models.PositiveIntegerField(
                        blank=True, help_text="Total quantity prescribed", null=True
                    ),
                ),
                (
                    "quantity_remaining",
                    models.PositiveIntegerField(
                        blank=True, help_text="Remaining quantity", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "prescription_medicines",
                "ordering": ["medicine_name"],
            },
        ),
        migrations.CreateModel(
            name="ReminderLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("scheduled_time", models.TimeField()),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("taken", "Taken"),
                            ("skipped", "Skipped"),
                            ("snoozed", "Snoozed"),
                            ("missed", "Missed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("snooze_count", models.PositiveSmallIntegerField(default=0)),
                ("last_snoozed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text='User notes like "Felt side effects"'
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "reminder_logs",
                "ordering": ["-scheduled_date", "-scheduled_time"],
            },
        ),
        migrations.CreateModel(
            name="UserPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text='e.g., "For Fever", "Diabetes Medication"',
                        max_length=255,
                    ),
                ),
                ("doctor_name", models.CharField(blank=True, max_length=255)),
                ("hospital_name", models.CharField(blank=True, max_length=255)),
                ("prescribed_date", models.DateField()),
                (
                    "valid_until",
                    models.DateField(
                        blank=True, help_text="Prescription validity", null=True
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(
                        blank=True, help_text="What condition is being treated"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("discontinued", "Discontinued"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "image_url",
                    models.URLField(
                        blank=True, help_text="Uploaded prescription image", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_prescriptions",
                "ordering": ["-prescribed_date"],
            },
        ),
    ]
