# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("medicine", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userprescription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prescriptions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reminderlog",
            name="reminder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="medicine.medicinereminder",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionmedicine",
            name="medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="in_prescriptions",
                to="medicine.medicine",
            ),
        ),
        migrations.AddField(
            model_name="prescriptionmedicine",
            name="prescription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicines",
                to="medicine.userprescription",
            ),
        ),
        migrations.AddField(
            model_name="medicinesearchhistory",
            name="medicine_found",
            field=models.ForeignKey(
                blank=True,
                help_text="If user clicked on a specific medicine",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="medicine.medicine",
            ),
        ),
        migrations.AddField(
            model_name="medicinesearchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine_searches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicinereminder",
            name="prescription_medicine",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="medicine.prescriptionmedicine",
            ),
        ),
        migrations.AddField(
            model_name="medicinereminder",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine_reminders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="medicinealternative",
            name="alternative",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternative_for",
                to="medicine.medicine",
            ),
        ),
        migrations.AddField(
            model_name="medicinealternative",
            name="medicine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alternatives",
                to="medicine.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["name", "is_active"], name="medicines_name_905584_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["name_generic", "is_active"],
                name="medicines_name_ge_ab451c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["category", "is_active"], name="medicines_categor_019dfd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["manufacturer"], name="medicines_manufac_63e646_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicine",
            index=models.Index(
                fields=["is_generic", "is_active"], name="medicines_is_gene_042db1_idx"
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="medicine_1",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_first",
                to="medicine.medicine",
            ),
        ),
        migrations.AddField(
            model_name="druginteraction",
            name="medicine_2",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions_as_second",
                to="medicine.medicine",
            ),
        ),
        migrations.AddIndex(
            model_name="userprescription",
            index=models.Index(
                fields=["user", "status"], name="user_prescr_user_id_acac84_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprescription",
            index=models.Index(
                fields=["user", "-prescribed_date"],
                name="user_prescr_user_id_20fc89_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["reminder", "scheduled_date"],
                name="reminder_lo_reminde_08957c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="reminderlog",
            index=models.Index(
                fields=["response", "scheduled_date"],
                name="reminder_lo_respons_9cf925_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="reminderlog",
            unique_together={("reminder", "scheduled_date", "scheduled_time")},
        ),
        migrations.AddIndex(
            model_name="medicinesearchhistory",
            index=models.Index(
                fields=["user", "-searched_at"], name="medicine_se_user_id_95af7e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicinereminder",
            index=models.Index(
                fields=["user", "status"], name="medicine_re_user_id_1d29ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="medicinereminder",
            index=models.Index(
                fields=["status", "start_date", "end_date"],
                name="medicine_re_status_dda8f7_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="medicinealternative",
            unique_together={("medicine", "alternative")},
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["medicine_1", "severity"], name="drug_intera_medicin_0c211f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="druginteraction",
            index=models.Index(
                fields=["medicine_2", "severity"], name="drug_intera_medicin_bc276c_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="druginteraction",
            unique_together={("medicine_1", "medicine_2")},
        ),
    ]
