# Generated by Django 4.2.17 on 2026-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medicine", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="prescriptionmedicine",
            index=models.Index(
                fields=["prescription", "is_active"],
                name="prescriptio_prescri_30629c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="prescriptionmedicine",
            index=models.Index(
                fields=["medicine_name"], name="prescriptio_medicin_b3350c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprescription",
            index=models.Index(
                fields=["user", "valid_until"], name="user_prescr_user_id_daeb97_idx"
            ),
        ),
    ]
