import uuid
from django.db import models
from django.conf import settings
from django.utils import timezone


class SyncAction(models.Model):
    """
    Represents a single offline action that needs to be synced.
    Created when frontend sends queued offline actions to backend.
    """
    
    ACTION_TYPES = [
        # Appointments
        ('appointment_create', 'Create Appointment'),
        ('appointment_cancel', 'Cancel Appointment'),
        ('appointment_reschedule', 'Reschedule Appointment'),
        
        # Consultations
        ('consultation_join', 'Join Consultation'),
        ('consultation_feedback', 'Submit Feedback'),
        
        # Medicine
        ('reminder_create', 'Create Reminder'),
        ('reminder_update', 'Update Reminder'),
        ('reminder_delete', 'Delete Reminder'),
        ('reminder_taken', 'Mark Medicine Taken'),
        ('reminder_skipped', 'Mark Medicine Skipped'),
        
        # Health Records
        ('vitals_create', 'Record Vitals'),
        ('condition_create', 'Add Condition'),
        ('condition_update', 'Update Condition'),
        ('allergy_create', 'Add Allergy'),
        ('document_upload', 'Upload Document'),
        
        # Emergency
        ('emergency_contact_create', 'Add Emergency Contact'),
        ('emergency_contact_update', 'Update Emergency Contact'),
        ('emergency_contact_delete', 'Delete Emergency Contact'),
        ('sos_trigger', 'Trigger SOS'),
        
        # Chatbot
        ('chat_message', 'Send Chat Message'),
        
        # Diagnosis
        ('diagnosis_create', 'Create Diagnosis'),
        
        # Profile
        ('profile_update', 'Update Profile'),
        
        # Notifications
        ('notification_read', 'Mark Notification Read'),
        ('device_register', 'Register Device'),
    ]
    
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('failed', 'Failed'),
        ('conflict', 'Conflict'),
        ('skipped', 'Skipped'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sync_actions'
    )
    
    # Action details
    action_type = models.CharField(max_length=50, choices=ACTION_TYPES)
    action_data = models.JSONField(help_text="The data payload for this action")
    
    # Client-side tracking
    client_action_id = models.CharField(
        max_length=100,
        help_text="Unique ID generated by frontend to prevent duplicates"
    )
    client_timestamp = models.DateTimeField(
        help_text="When the action was created on client device"
    )
    
    # Server-side tracking
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='pending')
    server_timestamp = models.DateTimeField(auto_now_add=True)
    processed_at = models.DateTimeField(null=True, blank=True)
    
    # Result
    result_data = models.JSONField(
        null=True, 
        blank=True,
        help_text="Result of processing (created object ID, error message, etc.)"
    )
    error_message = models.TextField(blank=True, null=True)
    retry_count = models.PositiveIntegerField(default=0)
    max_retries = models.PositiveIntegerField(default=3)
    
    # Versioning for conflict detection
    resource_type = models.CharField(
        max_length=50, 
        blank=True, 
        null=True,
        help_text="Type of resource being modified (appointment, reminder, etc.)"
    )
    resource_id = models.CharField(
        max_length=100, 
        blank=True, 
        null=True,
        help_text="ID of resource being modified"
    )
    resource_version = models.PositiveIntegerField(
        default=1,
        help_text="Version of resource when action was created offline"
    )
    
    class Meta:
        db_table = 'sync_actions'
        ordering = ['client_timestamp']
        indexes = [
            models.Index(fields=['user', 'status']),
            models.Index(fields=['user', 'client_action_id']),
            models.Index(fields=['status', 'server_timestamp']),
            models.Index(fields=['resource_type', 'resource_id']),
        ]
        unique_together = ['user', 'client_action_id']
    
    def __str__(self):
        return f"{self.user.phone} - {self.action_type} - {self.status}"
    
    def mark_completed(self, result_data=None):
        """Mark action as completed."""
        self.status = 'completed'
        self.processed_at = timezone.now()
        self.result_data = result_data
        self.save(update_fields=['status', 'processed_at', 'result_data'])
    
    def mark_failed(self, error_message):
        """Mark action as failed."""
        self.status = 'failed'
        self.processed_at = timezone.now()
        self.error_message = error_message
        self.retry_count += 1
        self.save(update_fields=['status', 'processed_at', 'error_message', 'retry_count'])
    
    def mark_conflict(self, conflict_details):
        """Mark action as having a conflict."""
        self.status = 'conflict'
        self.processed_at = timezone.now()
        self.result_data = conflict_details
        self.save(update_fields=['status', 'processed_at', 'result_data'])
    
    def can_retry(self):
        """Check if action can be retried."""
        return self.retry_count < self.max_retries and self.status == 'failed'


class SyncBatch(models.Model):
    """
    Represents a batch of sync actions pushed together from frontend.
    Groups multiple actions for efficient processing.
    """
    
    STATUS_CHOICES = [
        ('received', 'Received'),
        ('processing', 'Processing'),
        ('completed', 'Completed'),
        ('partial', 'Partially Completed'),
        ('failed', 'Failed'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sync_batches'
    )
    
    # Batch details
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='received')
    total_actions = models.PositiveIntegerField(default=0)
    completed_actions = models.PositiveIntegerField(default=0)
    failed_actions = models.PositiveIntegerField(default=0)
    conflict_actions = models.PositiveIntegerField(default=0)
    
    # Timestamps
    received_at = models.DateTimeField(auto_now_add=True)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    
    # Client info
    client_batch_id = models.CharField(
        max_length=100,
        help_text="Batch ID from frontend"
    )
    device_info = models.JSONField(
        null=True, 
        blank=True,
        help_text="Device information (type, OS, app version)"
    )
    
    class Meta:
        db_table = 'sync_batches'
        ordering = ['-received_at']
        indexes = [
            models.Index(fields=['user', 'status']),
            models.Index(fields=['user', 'client_batch_id']),
        ]
        unique_together = ['user', 'client_batch_id']
    
    def __str__(self):
        return f"{self.user.phone} - Batch {self.client_batch_id[:8]} - {self.status}"
    
    def update_counts(self):
        """Update action counts from related SyncActions."""
        actions = SyncAction.objects.filter(
            user=self.user,
            server_timestamp__gte=self.received_at
        )
        self.completed_actions = actions.filter(status='completed').count()
        self.failed_actions = actions.filter(status='failed').count()
        self.conflict_actions = actions.filter(status='conflict').count()
        
        if self.failed_actions == 0 and self.conflict_actions == 0:
            self.status = 'completed'
        elif self.completed_actions > 0:
            self.status = 'partial'
        else:
            self.status = 'failed'
        
        self.completed_at = timezone.now()
        self.save()


class SyncStatus(models.Model):
    """
    Tracks the overall sync status for each user.
    Maintains last sync timestamp and sync health.
    """
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sync_status'
    )
    
    # Sync timestamps
    last_push_at = models.DateTimeField(
        null=True, 
        blank=True,
        help_text="Last time user pushed offline actions"
    )
    last_pull_at = models.DateTimeField(
        null=True, 
        blank=True,
        help_text="Last time user pulled data from server"
    )
    last_full_sync_at = models.DateTimeField(
        null=True, 
        blank=True,
        help_text="Last time user did a full sync"
    )
    
    # Sync statistics
    total_pushes = models.PositiveIntegerField(default=0)
    total_pulls = models.PositiveIntegerField(default=0)
    total_conflicts = models.PositiveIntegerField(default=0)
    total_failed_actions = models.PositiveIntegerField(default=0)
    
    # Pending items
    pending_actions_count = models.PositiveIntegerField(default=0)
    unresolved_conflicts_count = models.PositiveIntegerField(default=0)
    
    # Device sync tracking
    last_device_info = models.JSONField(null=True, blank=True)
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'sync_status'
        verbose_name_plural = 'Sync Statuses'
    
    def __str__(self):
        return f"{self.user.phone} - Last sync: {self.last_push_at or 'Never'}"
    
    def update_push_stats(self):
        """Update statistics after a push operation."""
        self.last_push_at = timezone.now()
        self.total_pushes += 1
        self.pending_actions_count = SyncAction.objects.filter(
            user=self.user,
            status='pending'
        ).count()
        self.unresolved_conflicts_count = SyncAction.objects.filter(
            user=self.user,
            status='conflict'
        ).count()
        self.save()
    
    def update_pull_stats(self):
        """Update statistics after a pull operation."""
        self.last_pull_at = timezone.now()
        self.total_pulls += 1
        self.save(update_fields=['last_pull_at', 'total_pulls', 'updated_at'])


class ConflictRecord(models.Model):
    """
    Records conflicts that occur during sync for manual resolution.
    """
    
    CONFLICT_TYPES = [
        ('version_mismatch', 'Version Mismatch'),
        ('resource_deleted', 'Resource Deleted'),
        ('resource_modified', 'Resource Modified by Another'),
        ('slot_unavailable', 'Slot No Longer Available'),
        ('duplicate_action', 'Duplicate Action'),
        ('validation_error', 'Validation Error'),
        ('permission_denied', 'Permission Denied'),
    ]
    
    RESOLUTION_TYPES = [
        ('pending', 'Pending Resolution'),
        ('use_server', 'Use Server Version'),
        ('use_client', 'Use Client Version'),
        ('merge', 'Merged Both'),
        ('discard', 'Discarded'),
        ('auto_resolved', 'Auto Resolved'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sync_conflicts'
    )
    sync_action = models.ForeignKey(
        SyncAction,
        on_delete=models.CASCADE,
        related_name='conflicts'
    )
    
    # Conflict details
    conflict_type = models.CharField(max_length=30, choices=CONFLICT_TYPES)
    description = models.TextField(help_text="Human-readable conflict description")
    
    # Data comparison
    client_data = models.JSONField(help_text="Data from client (offline)")
    server_data = models.JSONField(help_text="Current data on server")
    
    # Resource info
    resource_type = models.CharField(max_length=50)
    resource_id = models.CharField(max_length=100)
    client_version = models.PositiveIntegerField()
    server_version = models.PositiveIntegerField()
    
    # Resolution
    resolution = models.CharField(
        max_length=20, 
        choices=RESOLUTION_TYPES, 
        default='pending'
    )
    resolved_data = models.JSONField(
        null=True, 
        blank=True,
        help_text="Final resolved data"
    )
    resolved_at = models.DateTimeField(null=True, blank=True)
    resolved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='resolved_conflicts'
    )
    
    # Timestamps
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'sync_conflicts'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'resolution']),
            models.Index(fields=['resource_type', 'resource_id']),
        ]
    
    def __str__(self):
        return f"{self.user.phone} - {self.conflict_type} - {self.resource_type}"
    
    def resolve(self, resolution, resolved_data=None, resolved_by=None):
        """Resolve the conflict."""
        self.resolution = resolution
        self.resolved_data = resolved_data
        self.resolved_at = timezone.now()
        self.resolved_by = resolved_by
        self.save()
        
        # Update sync action status
        if resolution in ['use_server', 'use_client', 'merge', 'auto_resolved']:
            self.sync_action.mark_completed(resolved_data)
        elif resolution == 'discard':
            self.sync_action.status = 'skipped'
            self.sync_action.save(update_fields=['status'])


class SyncLog(models.Model):
    """
    Detailed log of all sync operations for debugging and monitoring.
    """
    
    LOG_LEVELS = [
        ('debug', 'Debug'),
        ('info', 'Info'),
        ('warning', 'Warning'),
        ('error', 'Error'),
    ]
    
    OPERATION_TYPES = [
        ('push', 'Push'),
        ('pull', 'Pull'),
        ('process_action', 'Process Action'),
        ('conflict_detect', 'Conflict Detected'),
        ('conflict_resolve', 'Conflict Resolved'),
        ('retry', 'Retry'),
        ('rate_limit', 'Rate Limited'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='sync_logs',
        null=True,
        blank=True
    )
    
    # Log details
    level = models.CharField(max_length=10, choices=LOG_LEVELS, default='info')
    operation = models.CharField(max_length=30, choices=OPERATION_TYPES)
    message = models.TextField()
    
    # Related objects
    sync_action = models.ForeignKey(
        SyncAction,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='logs'
    )
    sync_batch = models.ForeignKey(
        SyncBatch,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='logs'
    )
    
    # Additional data
    extra_data = models.JSONField(null=True, blank=True)
    
    # Request info
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    user_agent = models.TextField(blank=True, null=True)
    
    # Timestamp
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'sync_logs'
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'operation']),
            models.Index(fields=['level', 'created_at']),
            models.Index(fields=['created_at']),
        ]
    
    def __str__(self):
        return f"{self.level.upper()} - {self.operation} - {self.message[:50]}"


class DataVersion(models.Model):
    """
    Tracks version numbers for different data types.
    Used for efficient delta sync (only sync changed data).
    """
    
    RESOURCE_TYPES = [
        ('appointment', 'Appointment'),
        ('consultation', 'Consultation'),
        ('prescription', 'Prescription'),
        ('reminder', 'Medicine Reminder'),
        ('health_profile', 'Health Profile'),
        ('vital_sign', 'Vital Sign'),
        ('condition', 'Medical Condition'),
        ('allergy', 'Allergy'),
        ('vaccination', 'Vaccination'),
        ('document', 'Document'),
        ('emergency_contact', 'Emergency Contact'),
        ('notification', 'Notification'),
        ('chat_session', 'Chat Session'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='data_versions'
    )
    
    resource_type = models.CharField(max_length=30, choices=RESOURCE_TYPES)
    resource_id = models.CharField(max_length=100)
    version = models.PositiveIntegerField(default=1)
    
    # Change tracking
    last_modified_at = models.DateTimeField(auto_now=True)
    last_modified_action = models.CharField(
        max_length=20,
        default='create',
        help_text="create, update, delete"
    )
    checksum = models.CharField(
        max_length=64,
        blank=True,
        null=True,
        help_text="MD5 hash of data for quick comparison"
    )
    
    class Meta:
        db_table = 'sync_data_versions'
        unique_together = ['user', 'resource_type', 'resource_id']
        indexes = [
            models.Index(fields=['user', 'resource_type']),
            models.Index(fields=['last_modified_at']),
        ]
    
    def __str__(self):
        return f"{self.resource_type}:{self.resource_id} v{self.version}"
    
    def increment_version(self, action='update'):
        """Increment version number."""
        self.version += 1
        self.last_modified_action = action
        self.save(update_fields=['version', 'last_modified_at', 'last_modified_action'])
        return self.version
    
    @classmethod
    def get_or_create_version(cls, user, resource_type, resource_id):
        """Get or create a version record."""
        version, created = cls.objects.get_or_create(
            user=user,
            resource_type=resource_type,
            resource_id=str(resource_id),
            defaults={'version': 1}
        )
        return version
    
    @classmethod
    def get_changes_since(cls, user, resource_type, since_timestamp):
        """Get all resources changed since a timestamp."""
        return cls.objects.filter(
            user=user,
            resource_type=resource_type,
            last_modified_at__gt=since_timestamp
        ).values_list('resource_id', flat=True)