"""
Serializers for Sync App

Handles serialization/deserialization of sync data
for API requests and responses.
"""

from rest_framework import serializers
from django.utils import timezone
from .models import (
    SyncAction,
    SyncBatch,
    SyncStatus,
    ConflictRecord,
    SyncLog,
    DataVersion
)


# =============================================================================
# SYNC ACTION SERIALIZERS
# =============================================================================

class SyncActionInputSerializer(serializers.Serializer):
    """
    Serializer for incoming sync action from frontend.
    """
    client_action_id = serializers.CharField(
        max_length=100,
        help_text="Unique ID generated by frontend"
    )
    action_type = serializers.ChoiceField(
        choices=[choice[0] for choice in SyncAction.ACTION_TYPES],
        help_text="Type of action"
    )
    data = serializers.JSONField(
        help_text="Action payload data"
    )
    client_timestamp = serializers.DateTimeField(
        required=False,
        help_text="When action was created on client"
    )
    resource_type = serializers.CharField(
        max_length=50,
        required=False,
        allow_blank=True,
        help_text="Type of resource being modified"
    )
    resource_id = serializers.CharField(
        max_length=100,
        required=False,
        allow_blank=True,
        help_text="ID of resource being modified"
    )
    resource_version = serializers.IntegerField(
        required=False,
        default=1,
        help_text="Version of resource when action was created"
    )
    
    def validate_client_timestamp(self, value):
        """Ensure timestamp is not in the future."""
        if value and value > timezone.now():
            # Allow some tolerance for clock differences
            max_future = timezone.now() + timezone.timedelta(minutes=5)
            if value > max_future:
                raise serializers.ValidationError(
                    "Timestamp cannot be more than 5 minutes in the future"
                )
        return value


class SyncActionOutputSerializer(serializers.ModelSerializer):
    """
    Serializer for sync action output/response.
    """
    class Meta:
        model = SyncAction
        fields = [
            'id',
            'action_type',
            'action_data',
            'client_action_id',
            'client_timestamp',
            'server_timestamp',
            'status',
            'processed_at',
            'result_data',
            'error_message',
            'retry_count',
            'resource_type',
            'resource_id',
            'resource_version',
        ]
        read_only_fields = fields


class SyncActionDetailSerializer(serializers.ModelSerializer):
    """
    Detailed serializer for sync action with all fields.
    """
    user_phone = serializers.CharField(source='user.phone', read_only=True)
    can_retry = serializers.SerializerMethodField()
    
    class Meta:
        model = SyncAction
        fields = [
            'id',
            'user_phone',
            'action_type',
            'action_data',
            'client_action_id',
            'client_timestamp',
            'server_timestamp',
            'status',
            'processed_at',
            'result_data',
            'error_message',
            'retry_count',
            'max_retries',
            'can_retry',
            'resource_type',
            'resource_id',
            'resource_version',
        ]
        read_only_fields = fields
    
    def get_can_retry(self, obj):
        return obj.can_retry()


# =============================================================================
# SYNC BATCH SERIALIZERS
# =============================================================================

class SyncBatchSerializer(serializers.ModelSerializer):
    """
    Serializer for sync batch.
    """
    user_phone = serializers.CharField(source='user.phone', read_only=True)
    duration_seconds = serializers.SerializerMethodField()
    
    class Meta:
        model = SyncBatch
        fields = [
            'id',
            'user_phone',
            'client_batch_id',
            'status',
            'total_actions',
            'completed_actions',
            'failed_actions',
            'conflict_actions',
            'received_at',
            'started_at',
            'completed_at',
            'duration_seconds',
            'device_info',
        ]
        read_only_fields = fields
    
    def get_duration_seconds(self, obj):
        if obj.started_at and obj.completed_at:
            delta = obj.completed_at - obj.started_at
            return delta.total_seconds()
        return None


# =============================================================================
# PUSH REQUEST/RESPONSE SERIALIZERS
# =============================================================================

class PushRequestSerializer(serializers.Serializer):
    """
    Serializer for push sync request.
    """
    batch_id = serializers.CharField(
        max_length=100,
        help_text="Client-generated batch ID for idempotency"
    )
    actions = SyncActionInputSerializer(
        many=True,
        help_text="List of offline actions to sync"
    )
    device_info = serializers.JSONField(
        required=False,
        help_text="Device information"
    )
    
    def validate_actions(self, value):
        """Validate actions list."""
        if not value:
            raise serializers.ValidationError("At least one action is required")
        if len(value) > 50:
            raise serializers.ValidationError("Maximum 50 actions per request")
        
        # Check for duplicate client_action_ids within batch
        action_ids = [a['client_action_id'] for a in value]
        if len(action_ids) != len(set(action_ids)):
            raise serializers.ValidationError(
                "Duplicate client_action_id found in batch"
            )
        
        return value


class PushActionResultSerializer(serializers.Serializer):
    """
    Serializer for individual action result in push response.
    """
    action_id = serializers.UUIDField()
    client_action_id = serializers.CharField()
    action_type = serializers.CharField()
    status = serializers.CharField()
    message = serializers.CharField(required=False, allow_null=True)
    result_data = serializers.JSONField(required=False, allow_null=True)


class PushResponseSerializer(serializers.Serializer):
    """
    Serializer for push sync response.
    """
    success = serializers.BooleanField()
    message = serializers.CharField()
    batch_id = serializers.UUIDField(required=False)
    status = serializers.CharField(required=False)
    summary = serializers.DictField(required=False)
    results = PushActionResultSerializer(many=True, required=False)
    rate_limit = serializers.DictField(required=False)
    error = serializers.CharField(required=False)
    retry_after = serializers.IntegerField(required=False)


# =============================================================================
# PULL REQUEST/RESPONSE SERIALIZERS
# =============================================================================

class PullRequestSerializer(serializers.Serializer):
    """
    Serializer for pull sync request.
    """
    since = serializers.DateTimeField(
        required=False,
        help_text="Only get data modified after this timestamp"
    )
    data_types = serializers.ListField(
        child=serializers.CharField(),
        required=False,
        help_text="List of data types to pull (empty = all)"
    )
    full_sync = serializers.BooleanField(
        required=False,
        default=False,
        help_text="If true, ignore 'since' and get all data"
    )
    
    def validate_data_types(self, value):
        """Validate data types."""
        valid_types = [
            'appointments', 'consultations', 'prescriptions',
            'reminders', 'health_profile', 'vital_signs',
            'conditions', 'allergies', 'vaccinations',
            'documents', 'emergency_contacts', 'notifications',
            'chat_sessions'
        ]
        
        if value:
            invalid = [dt for dt in value if dt not in valid_types]
            if invalid:
                raise serializers.ValidationError(
                    f"Invalid data types: {invalid}. Valid types: {valid_types}"
                )
        
        return value


class PullDataItemSerializer(serializers.Serializer):
    """
    Generic serializer for pull data items.
    """
    items = serializers.ListField(child=serializers.DictField())
    total = serializers.IntegerField()
    error = serializers.CharField(required=False, allow_null=True)
    unchanged = serializers.BooleanField(required=False, default=False)


class PullResponseSerializer(serializers.Serializer):
    """
    Serializer for pull sync response.
    """
    success = serializers.BooleanField()
    message = serializers.CharField()
    sync_timestamp = serializers.DateTimeField(required=False)
    since = serializers.DateTimeField(required=False, allow_null=True)
    full_sync = serializers.BooleanField(required=False)
    data = serializers.DictField(required=False)
    conflicts = serializers.ListField(
        child=serializers.DictField(),
        required=False
    )
    has_more_conflicts = serializers.BooleanField(required=False)
    rate_limit = serializers.DictField(required=False)
    error = serializers.CharField(required=False)


# =============================================================================
# SYNC STATUS SERIALIZERS
# =============================================================================

class SyncStatusSerializer(serializers.ModelSerializer):
    """
    Serializer for sync status.
    """
    user_phone = serializers.CharField(source='user.phone', read_only=True)
    
    class Meta:
        model = SyncStatus
        fields = [
            'id',
            'user_phone',
            'last_push_at',
            'last_pull_at',
            'last_full_sync_at',
            'total_pushes',
            'total_pulls',
            'total_conflicts',
            'total_failed_actions',
            'pending_actions_count',
            'unresolved_conflicts_count',
            'last_device_info',
            'created_at',
            'updated_at',
        ]
        read_only_fields = fields


class SyncStatusResponseSerializer(serializers.Serializer):
    """
    Serializer for sync status API response.
    """
    success = serializers.BooleanField()
    status = serializers.DictField()
    queue = serializers.DictField()
    conflicts = serializers.DictField()
    rate_limit = serializers.DictField()
    is_syncing = serializers.BooleanField()


# =============================================================================
# CONFLICT SERIALIZERS
# =============================================================================

class ConflictRecordSerializer(serializers.ModelSerializer):
    """
    Serializer for conflict record.
    """
    user_phone = serializers.CharField(source='user.phone', read_only=True)
    sync_action_id = serializers.UUIDField(source='sync_action.id', read_only=True)
    sync_action_type = serializers.CharField(
        source='sync_action.action_type',
        read_only=True
    )
    
    class Meta:
        model = ConflictRecord
        fields = [
            'id',
            'user_phone',
            'sync_action_id',
            'sync_action_type',
            'conflict_type',
            'description',
            'client_data',
            'server_data',
            'resource_type',
            'resource_id',
            'client_version',
            'server_version',
            'resolution',
            'resolved_data',
            'resolved_at',
            'created_at',
            'updated_at',
        ]
        read_only_fields = fields


class ConflictListSerializer(serializers.ModelSerializer):
    """
    Simplified serializer for conflict list view.
    """
    class Meta:
        model = ConflictRecord
        fields = [
            'id',
            'conflict_type',
            'resource_type',
            'resource_id',
            'description',
            'resolution',
            'created_at',
        ]
        read_only_fields = fields


class ResolveConflictRequestSerializer(serializers.Serializer):
    """
    Serializer for conflict resolution request.
    """
    resolution = serializers.ChoiceField(
        choices=['use_server', 'use_client', 'merge', 'discard'],
        help_text="How to resolve the conflict"
    )
    custom_data = serializers.JSONField(
        required=False,
        allow_null=True,
        help_text="Custom merged data (required for 'merge' resolution)"
    )
    
    def validate(self, data):
        """Validate resolution request."""
        if data['resolution'] == 'merge' and not data.get('custom_data'):
            raise serializers.ValidationError({
                'custom_data': "Custom data is required for 'merge' resolution"
            })
        return data


class ResolveConflictResponseSerializer(serializers.Serializer):
    """
    Serializer for conflict resolution response.
    """
    success = serializers.BooleanField()
    message = serializers.CharField()
    resolution = serializers.CharField(required=False)
    resolved_data = serializers.JSONField(required=False, allow_null=True)
    error = serializers.CharField(required=False)


# =============================================================================
# SYNC LOG SERIALIZERS
# =============================================================================

class SyncLogSerializer(serializers.ModelSerializer):
    """
    Serializer for sync log.
    """
    user_phone = serializers.CharField(
        source='user.phone',
        read_only=True,
        allow_null=True
    )
    
    class Meta:
        model = SyncLog
        fields = [
            'id',
            'user_phone',
            'level',
            'operation',
            'message',
            'extra_data',
            'ip_address',
            'user_agent',
            'created_at',
        ]
        read_only_fields = fields


class SyncLogListSerializer(serializers.ModelSerializer):
    """
    Simplified serializer for sync log list.
    """
    class Meta:
        model = SyncLog
        fields = [
            'id',
            'level',
            'operation',
            'message',
            'created_at',
        ]
        read_only_fields = fields


# =============================================================================
# DATA VERSION SERIALIZERS
# =============================================================================

class DataVersionSerializer(serializers.ModelSerializer):
    """
    Serializer for data version.
    """
    user_phone = serializers.CharField(source='user.phone', read_only=True)
    
    class Meta:
        model = DataVersion
        fields = [
            'id',
            'user_phone',
            'resource_type',
            'resource_id',
            'version',
            'last_modified_at',
            'last_modified_action',
            'checksum',
        ]
        read_only_fields = fields


# =============================================================================
# RETRY SERIALIZERS
# =============================================================================

class RetryRequestSerializer(serializers.Serializer):
    """
    Serializer for retry failed actions request.
    """
    max_actions = serializers.IntegerField(
        required=False,
        default=10,
        min_value=1,
        max_value=50,
        help_text="Maximum number of actions to retry"
    )
    action_ids = serializers.ListField(
        child=serializers.UUIDField(),
        required=False,
        help_text="Specific action IDs to retry (optional)"
    )


class RetryResponseSerializer(serializers.Serializer):
    """
    Serializer for retry response.
    """
    success = serializers.BooleanField()
    message = serializers.CharField()
    results = serializers.DictField(required=False)
    error = serializers.CharField(required=False)


# =============================================================================
# HEALTH CHECK SERIALIZER
# =============================================================================

class HealthCheckSerializer(serializers.Serializer):
    """
    Serializer for health check response.
    """
    status = serializers.CharField()
    service = serializers.CharField()
    version = serializers.CharField()
    timestamp = serializers.DateTimeField()
    components = serializers.DictField()


# =============================================================================
# QUICK DATA SERIALIZER
# =============================================================================

class QuickSyncDataSerializer(serializers.Serializer):
    """
    Serializer for quick sync data (dashboard summary).
    """
    last_sync = serializers.DateTimeField(allow_null=True)
    pending_actions = serializers.IntegerField()
    unresolved_conflicts = serializers.IntegerField()
    failed_actions = serializers.IntegerField()
    is_syncing = serializers.BooleanField()
    needs_sync = serializers.BooleanField()
    sync_health = serializers.CharField()


# =============================================================================
# DEVICE INFO SERIALIZER
# =============================================================================

class DeviceInfoSerializer(serializers.Serializer):
    """
    Serializer for device information.
    """
    device_type = serializers.ChoiceField(
        choices=['android', 'ios', 'web'],
        required=False
    )
    device_name = serializers.CharField(max_length=100, required=False)
    os_version = serializers.CharField(max_length=50, required=False)
    app_version = serializers.CharField(max_length=20, required=False)
    browser = serializers.CharField(max_length=50, required=False)
    screen_width = serializers.IntegerField(required=False)
    screen_height = serializers.IntegerField(required=False)
    timezone = serializers.CharField(max_length=50, required=False)
    language = serializers.CharField(max_length=10, required=False)


# =============================================================================
# BULK OPERATIONS SERIALIZERS
# =============================================================================

class BulkResolveConflictsRequestSerializer(serializers.Serializer):
    """
    Serializer for bulk conflict resolution.
    """
    conflict_ids = serializers.ListField(
        child=serializers.UUIDField(),
        min_length=1,
        max_length=50,
        help_text="List of conflict IDs to resolve"
    )
    resolution = serializers.ChoiceField(
        choices=['use_server', 'use_client', 'discard'],
        help_text="Resolution to apply to all conflicts"
    )


class BulkResolveConflictsResponseSerializer(serializers.Serializer):
    """
    Serializer for bulk conflict resolution response.
    """
    success = serializers.BooleanField()
    message = serializers.CharField()
    results = serializers.DictField()


class ClearSyncDataRequestSerializer(serializers.Serializer):
    """
    Serializer for clearing sync data request.
    """
    clear_actions = serializers.BooleanField(
        required=False,
        default=False,
        help_text="Clear all sync actions"
    )
    clear_conflicts = serializers.BooleanField(
        required=False,
        default=False,
        help_text="Clear all conflicts"
    )
    clear_logs = serializers.BooleanField(
        required=False,
        default=False,
        help_text="Clear all sync logs"
    )
    older_than_days = serializers.IntegerField(
        required=False,
        default=30,
        min_value=1,
        max_value=365,
        help_text="Only clear data older than this many days"
    )
    
    def validate(self, data):
        """Ensure at least one clear option is selected."""
        if not any([
            data.get('clear_actions'),
            data.get('clear_conflicts'),
            data.get('clear_logs')
        ]):
            raise serializers.ValidationError(
                "At least one clear option must be selected"
            )
        return data