# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConflictRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "conflict_type",
                    models.CharField(
                        choices=[
                            ("version_mismatch", "Version Mismatch"),
                            ("resource_deleted", "Resource Deleted"),
                            ("resource_modified", "Resource Modified by Another"),
                            ("slot_unavailable", "Slot No Longer Available"),
                            ("duplicate_action", "Duplicate Action"),
                            ("validation_error", "Validation Error"),
                            ("permission_denied", "Permission Denied"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Human-readable conflict description"),
                ),
                (
                    "client_data",
                    models.JSONField(help_text="Data from client (offline)"),
                ),
                ("server_data", models.JSONField(help_text="Current data on server")),
                ("resource_type", models.CharField(max_length=50)),
                ("resource_id", models.CharField(max_length=100)),
                ("client_version", models.PositiveIntegerField()),
                ("server_version", models.PositiveIntegerField()),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Resolution"),
                            ("use_server", "Use Server Version"),
                            ("use_client", "Use Client Version"),
                            ("merge", "Merged Both"),
                            ("discard", "Discarded"),
                            ("auto_resolved", "Auto Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resolved_data",
                    models.JSONField(
                        blank=True, help_text="Final resolved data", null=True
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sync_conflicts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DataVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("appointment", "Appointment"),
                            ("consultation", "Consultation"),
                            ("prescription", "Prescription"),
                            ("reminder", "Medicine Reminder"),
                            ("health_profile", "Health Profile"),
                            ("vital_sign", "Vital Sign"),
                            ("condition", "Medical Condition"),
                            ("allergy", "Allergy"),
                            ("vaccination", "Vaccination"),
                            ("document", "Document"),
                            ("emergency_contact", "Emergency Contact"),
                            ("notification", "Notification"),
                            ("chat_session", "Chat Session"),
                        ],
                        max_length=30,
                    ),
                ),
                ("resource_id", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField(default=1)),
                ("last_modified_at", models.DateTimeField(auto_now=True)),
                (
                    "last_modified_action",
                    models.CharField(
                        default="create",
                        help_text="create, update, delete",
                        max_length=20,
                    ),
                ),
                (
                    "checksum",
                    models.CharField(
                        blank=True,
                        help_text="MD5 hash of data for quick comparison",
                        max_length=64,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "sync_data_versions",
            },
        ),
        migrations.CreateModel(
            name="SyncAction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("appointment_create", "Create Appointment"),
                            ("appointment_cancel", "Cancel Appointment"),
                            ("appointment_reschedule", "Reschedule Appointment"),
                            ("consultation_join", "Join Consultation"),
                            ("consultation_feedback", "Submit Feedback"),
                            ("reminder_create", "Create Reminder"),
                            ("reminder_update", "Update Reminder"),
                            ("reminder_delete", "Delete Reminder"),
                            ("reminder_taken", "Mark Medicine Taken"),
                            ("reminder_skipped", "Mark Medicine Skipped"),
                            ("vitals_create", "Record Vitals"),
                            ("condition_create", "Add Condition"),
                            ("condition_update", "Update Condition"),
                            ("allergy_create", "Add Allergy"),
                            ("document_upload", "Upload Document"),
                            ("emergency_contact_create", "Add Emergency Contact"),
                            ("emergency_contact_update", "Update Emergency Contact"),
                            ("emergency_contact_delete", "Delete Emergency Contact"),
                            ("sos_trigger", "Trigger SOS"),
                            ("chat_message", "Send Chat Message"),
                            ("diagnosis_create", "Create Diagnosis"),
                            ("profile_update", "Update Profile"),
                            ("notification_read", "Mark Notification Read"),
                            ("device_register", "Register Device"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action_data",
                    models.JSONField(help_text="The data payload for this action"),
                ),
                (
                    "client_action_id",
                    models.CharField(
                        help_text="Unique ID generated by frontend to prevent duplicates",
                        max_length=100,
                    ),
                ),
                (
                    "client_timestamp",
                    models.DateTimeField(
                        help_text="When the action was created on client device"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("conflict", "Conflict"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("server_timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "result_data",
                    models.JSONField(
                        blank=True,
                        help_text="Result of processing (created object ID, error message, etc.)",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "resource_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of resource being modified (appointment, reminder, etc.)",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of resource being modified",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "resource_version",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Version of resource when action was created offline",
                    ),
                ),
            ],
            options={
                "db_table": "sync_actions",
                "ordering": ["client_timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SyncBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("partial", "Partially Completed"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("total_actions", models.PositiveIntegerField(default=0)),
                ("completed_actions", models.PositiveIntegerField(default=0)),
                ("failed_actions", models.PositiveIntegerField(default=0)),
                ("conflict_actions", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "client_batch_id",
                    models.CharField(
                        help_text="Batch ID from frontend", max_length=100
                    ),
                ),
                (
                    "device_info",
                    models.JSONField(
                        blank=True,
                        help_text="Device information (type, OS, app version)",
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "sync_batches",
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("push", "Push"),
                            ("pull", "Pull"),
                            ("process_action", "Process Action"),
                            ("conflict_detect", "Conflict Detected"),
                            ("conflict_resolve", "Conflict Resolved"),
                            ("retry", "Retry"),
                            ("rate_limit", "Rate Limited"),
                        ],
                        max_length=30,
                    ),
                ),
                ("message", models.TextField()),
                ("extra_data", models.JSONField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "sync_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyncStatus",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_push_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user pushed offline actions",
                        null=True,
                    ),
                ),
                (
                    "last_pull_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user pulled data from server",
                        null=True,
                    ),
                ),
                (
                    "last_full_sync_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time user did a full sync",
                        null=True,
                    ),
                ),
                ("total_pushes", models.PositiveIntegerField(default=0)),
                ("total_pulls", models.PositiveIntegerField(default=0)),
                ("total_conflicts", models.PositiveIntegerField(default=0)),
                ("total_failed_actions", models.PositiveIntegerField(default=0)),
                ("pending_actions_count", models.PositiveIntegerField(default=0)),
                ("unresolved_conflicts_count", models.PositiveIntegerField(default=0)),
                ("last_device_info", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Sync Statuses",
                "db_table": "sync_status",
            },
        ),
    ]
