# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sync", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="syncstatus",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_status",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="sync_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="sync.syncaction",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="sync_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logs",
                to="sync.syncbatch",
            ),
        ),
        migrations.AddField(
            model_name="synclog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncbatch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="syncaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dataversion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data_versions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conflictrecord",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_conflicts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conflictrecord",
            name="sync_action",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="conflicts",
                to="sync.syncaction",
            ),
        ),
        migrations.AddField(
            model_name="conflictrecord",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sync_conflicts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["user", "operation"], name="sync_logs_user_id_44646d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["level", "created_at"], name="sync_logs_level_abad05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="synclog",
            index=models.Index(
                fields=["created_at"], name="sync_logs_created_07d9f3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncbatch",
            index=models.Index(
                fields=["user", "status"], name="sync_batche_user_id_f951f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncbatch",
            index=models.Index(
                fields=["user", "client_batch_id"],
                name="sync_batche_user_id_d9d6d6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncbatch",
            unique_together={("user", "client_batch_id")},
        ),
        migrations.AddIndex(
            model_name="syncaction",
            index=models.Index(
                fields=["user", "status"], name="sync_action_user_id_88fc7c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="syncaction",
            index=models.Index(
                fields=["user", "client_action_id"],
                name="sync_action_user_id_d4f185_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncaction",
            index=models.Index(
                fields=["status", "server_timestamp"],
                name="sync_action_status_68756a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="syncaction",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="sync_action_resourc_abd055_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="syncaction",
            unique_together={("user", "client_action_id")},
        ),
        migrations.AddIndex(
            model_name="dataversion",
            index=models.Index(
                fields=["user", "resource_type"], name="sync_data_v_user_id_32bdee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dataversion",
            index=models.Index(
                fields=["last_modified_at"], name="sync_data_v_last_mo_bbd131_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dataversion",
            unique_together={("user", "resource_type", "resource_id")},
        ),
        migrations.AddIndex(
            model_name="conflictrecord",
            index=models.Index(
                fields=["user", "resolution"], name="sync_confli_user_id_233659_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conflictrecord",
            index=models.Index(
                fields=["resource_type", "resource_id"],
                name="sync_confli_resourc_e1b99c_idx",
            ),
        ),
    ]
