# Generated by Django 4.2.17 on 2026-03-11 10:44

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number starting with 6-9",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "alternate_phone",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-digit Indian mobile number starting with 6-9",
                                regex="^[6-9]\\d{9}$",
                            )
                        ],
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse"),
                            ("parent", "Parent"),
                            ("child", "Child"),
                            ("sibling", "Sibling"),
                            ("relative", "Relative"),
                            ("friend", "Friend"),
                            ("neighbor", "Neighbor"),
                            ("doctor", "Doctor"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="1 = Highest priority, 10 = Lowest",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "notify_on_sos",
                    models.BooleanField(
                        default=True, help_text="Send SMS/notification during SOS"
                    ),
                ),
                (
                    "share_location",
                    models.BooleanField(
                        default=True, help_text="Share GPS location during SOS"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "emergency_contacts",
                "ordering": ["priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyHelpline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_en", models.CharField(max_length=100)),
                ("name_te", models.CharField(blank=True, max_length=100)),
                ("name_hi", models.CharField(blank=True, max_length=100)),
                (
                    "helpline_type",
                    models.CharField(
                        choices=[
                            ("ambulance", "Ambulance"),
                            ("police", "Police"),
                            ("fire", "Fire"),
                            ("women", "Women Helpline"),
                            ("child", "Child Helpline"),
                            ("disaster", "Disaster Management"),
                            ("poison", "Poison Control"),
                            ("mental_health", "Mental Health"),
                            ("covid", "COVID Helpline"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("number", models.CharField(max_length=15)),
                ("alternate_number", models.CharField(blank=True, max_length=15)),
                ("is_national", models.BooleanField(default=True)),
                (
                    "state",
                    models.CharField(
                        blank=True,
                        help_text="Applicable state if not national",
                        max_length=100,
                    ),
                ),
                ("description_en", models.TextField(blank=True)),
                ("description_te", models.TextField(blank=True)),
                ("description_hi", models.TextField(blank=True)),
                ("is_24x7", models.BooleanField(default=True)),
                ("is_toll_free", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "emergency_helplines",
                "ordering": ["display_order", "helpline_type"],
            },
        ),
        migrations.CreateModel(
            name="EmergencyService",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "name_local",
                    models.CharField(
                        blank=True,
                        help_text="Name in local language (Telugu/Hindi)",
                        max_length=200,
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("hospital", "Hospital"),
                            ("clinic", "Clinic"),
                            ("phc", "Primary Health Center"),
                            ("ambulance", "Ambulance Service"),
                            ("helpline", "Emergency Helpline"),
                            ("blood_bank", "Blood Bank"),
                            ("pharmacy", "Pharmacy (24/7)"),
                            ("police", "Police Station"),
                            ("fire", "Fire Station"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "facility_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tertiary", "Tertiary"),
                            ("specialized", "Specialized"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("phone_primary", models.CharField(max_length=15)),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "phone_emergency",
                    models.CharField(
                        blank=True,
                        help_text="Dedicated emergency line if different",
                        max_length=15,
                        null=True,
                    ),
                ),
                ("address", models.TextField()),
                (
                    "address_local",
                    models.TextField(blank=True, help_text="Address in local language"),
                ),
                ("landmark", models.CharField(blank=True, max_length=200)),
                ("district", models.CharField(max_length=100)),
                ("state", models.CharField(default="Andhra Pradesh", max_length=100)),
                ("pincode", models.CharField(max_length=6)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                ("is_24x7", models.BooleanField(default=False)),
                ("opening_time", models.TimeField(blank=True, null=True)),
                ("closing_time", models.TimeField(blank=True, null=True)),
                ("has_emergency_ward", models.BooleanField(default=False)),
                ("has_icu", models.BooleanField(default=False)),
                ("has_ambulance", models.BooleanField(default=False)),
                ("has_blood_bank", models.BooleanField(default=False)),
                ("bed_count", models.PositiveIntegerField(default=0)),
                ("is_government", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "emergency_services",
                "ordering": ["service_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="FirstAidGuide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title_en", models.CharField(max_length=200)),
                ("title_te", models.CharField(blank=True, max_length=200)),
                ("title_hi", models.CharField(blank=True, max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("bleeding", "Bleeding"),
                            ("burns", "Burns"),
                            ("choking", "Choking"),
                            ("cpr", "CPR"),
                            ("fracture", "Fractures"),
                            ("heart_attack", "Heart Attack"),
                            ("stroke", "Stroke"),
                            ("poisoning", "Poisoning"),
                            ("snake_bite", "Snake Bite"),
                            ("dog_bite", "Dog/Animal Bite"),
                            ("drowning", "Drowning"),
                            ("electric_shock", "Electric Shock"),
                            ("fainting", "Fainting"),
                            ("seizure", "Seizure"),
                            ("heat_stroke", "Heat Stroke"),
                            ("pregnancy", "Pregnancy Emergency"),
                            ("child", "Child Emergency"),
                            ("allergy", "Allergic Reaction"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "symptoms_en",
                    models.TextField(help_text="How to identify this emergency"),
                ),
                ("symptoms_te", models.TextField(blank=True)),
                ("symptoms_hi", models.TextField(blank=True)),
                (
                    "steps_en",
                    models.JSONField(
                        default=list, help_text="List of steps in English"
                    ),
                ),
                ("steps_te", models.JSONField(blank=True, default=list)),
                ("steps_hi", models.JSONField(blank=True, default=list)),
                (
                    "donts_en",
                    models.JSONField(default=list, help_text="What NOT to do"),
                ),
                ("donts_te", models.JSONField(blank=True, default=list)),
                ("donts_hi", models.JSONField(blank=True, default=list)),
                (
                    "call_help_en",
                    models.TextField(
                        blank=True, help_text="When to call ambulance/doctor"
                    ),
                ),
                ("call_help_te", models.TextField(blank=True)),
                ("call_help_hi", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("video_url", models.URLField(blank=True, null=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Show prominently for life-threatening emergencies",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "first_aid_guides",
                "ordering": ["display_order", "title_en"],
            },
        ),
        migrations.CreateModel(
            name="SOSAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "emergency_type",
                    models.CharField(
                        choices=[
                            ("medical", "Medical Emergency"),
                            ("accident", "Accident"),
                            ("heart", "Heart Attack/Chest Pain"),
                            ("breathing", "Breathing Difficulty"),
                            ("unconscious", "Person Unconscious"),
                            ("bleeding", "Severe Bleeding"),
                            ("burn", "Burn Injury"),
                            ("poison", "Poisoning"),
                            ("snake_bite", "Snake Bite"),
                            ("pregnancy", "Pregnancy Emergency"),
                            ("child", "Child Emergency"),
                            ("other", "Other Emergency"),
                        ],
                        default="medical",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("triggered", "Triggered"),
                            ("notifying", "Notifying Contacts"),
                            ("acknowledged", "Acknowledged"),
                            ("responding", "Help Responding"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled by User"),
                            ("false_alarm", "False Alarm"),
                        ],
                        default="triggered",
                        max_length=20,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "location_address",
                    models.TextField(blank=True, help_text="Reverse geocoded address"),
                ),
                (
                    "location_accuracy",
                    models.FloatField(
                        blank=True, help_text="GPS accuracy in meters", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="User provided details about emergency"
                    ),
                ),
                (
                    "voice_note_url",
                    models.URLField(
                        blank=True,
                        help_text="Voice message if user recorded one",
                        null=True,
                    ),
                ),
                (
                    "contacts_notified",
                    models.JSONField(
                        default=list, help_text="List of contact IDs that were notified"
                    ),
                ),
                (
                    "services_notified",
                    models.JSONField(
                        default=list,
                        help_text="List of emergency service IDs contacted",
                    ),
                ),
                ("notification_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "acknowledged_by",
                    models.CharField(
                        blank=True,
                        help_text="Name of person who acknowledged",
                        max_length=100,
                    ),
                ),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "responder_eta",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Estimated time of arrival in minutes",
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "sos_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserLocationCache",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=11, null=True
                    ),
                ),
                (
                    "accuracy",
                    models.FloatField(
                        blank=True, help_text="Accuracy in meters", null=True
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("district", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=6)),
                (
                    "nearby_hospitals",
                    models.JSONField(
                        default=list, help_text="Cached list of nearby hospital IDs"
                    ),
                ),
                (
                    "nearby_ambulances",
                    models.JSONField(
                        default=list,
                        help_text="Cached list of nearby ambulance service IDs",
                    ),
                ),
                ("location_updated_at", models.DateTimeField(auto_now=True)),
                ("nearby_updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_location_cache",
            },
        ),
    ]
