# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emergency", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocationcache",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="location_cache",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sosalert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sos_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="firstaidguide",
            index=models.Index(
                fields=["category", "is_active"], name="first_aid_g_categor_a1b097_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="firstaidguide",
            index=models.Index(
                fields=["is_critical", "is_active"],
                name="first_aid_g_is_crit_2828b7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyservice",
            index=models.Index(
                fields=["service_type", "is_active"],
                name="emergency_s_service_acec8d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyservice",
            index=models.Index(
                fields=["district", "service_type"],
                name="emergency_s_distric_b7a3d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyservice",
            index=models.Index(
                fields=["latitude", "longitude"], name="emergency_s_latitud_54ab40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyservice",
            index=models.Index(
                fields=["pincode"], name="emergency_s_pincode_99008f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyhelpline",
            index=models.Index(
                fields=["helpline_type", "is_active"],
                name="emergency_h_helplin_9944f3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emergencyhelpline",
            index=models.Index(
                fields=["is_national", "state"], name="emergency_h_is_nati_a567c5_idx"
            ),
        ),
        migrations.AddField(
            model_name="emergencycontact",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emergency_contacts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="sosalert",
            index=models.Index(
                fields=["user", "status"], name="sos_alerts_user_id_e73d87_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sosalert",
            index=models.Index(
                fields=["status", "created_at"], name="sos_alerts_status_59beea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sosalert",
            index=models.Index(
                fields=["emergency_type"], name="sos_alerts_emergen_7645b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sosalert",
            index=models.Index(
                fields=["-created_at"], name="sos_alerts_created_712e49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["user", "is_active"], name="emergency_c_user_id_9c63b0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emergencycontact",
            index=models.Index(
                fields=["user", "priority"], name="emergency_c_user_id_2eac98_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emergencycontact",
            unique_together={("user", "phone_number")},
        ),
    ]
