# Generated by Django 4.2.17 on 2026-01-24 13:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiagnosisSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("voice", "Voice"),
                            ("selection", "Symptom Selection"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                (
                    "raw_input",
                    models.TextField(help_text="Original text/transcription from user"),
                ),
                (
                    "input_language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "translated_input",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Input translated to English for processing",
                    ),
                ),
                ("patient_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "patient_gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "symptom_duration_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="How many days symptoms have been present",
                        null=True,
                    ),
                ),
                (
                    "extracted_symptoms",
                    models.JSONField(
                        default=list,
                        help_text="List of symptom codes extracted from input",
                    ),
                ),
                (
                    "extraction_confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "predictions",
                    models.JSONField(
                        default=list,
                        help_text="List of predicted diseases with confidence scores",
                    ),
                ),
                (
                    "top_prediction_confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "severity_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "severity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Severity score 0-100",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "recommended_specialist",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="List of recommendations/precautions"
                    ),
                ),
                ("requires_emergency_care", models.BooleanField(default=False)),
                ("response_text", models.TextField(blank=True, default="")),
                (
                    "response_language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "user_feedback",
                    models.CharField(
                        choices=[
                            ("none", "No Feedback"),
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                            ("incorrect", "Incorrect"),
                        ],
                        default="none",
                        max_length=15,
                    ),
                ),
                ("feedback_comment", models.TextField(blank=True, default="")),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        default=0, help_text="Time taken to process in milliseconds"
                    ),
                ),
                (
                    "device_type",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Diagnosis Session",
                "verbose_name_plural": "Diagnosis Sessions",
                "db_table": "diagnosis_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code like 'fungal_infection', 'common_cold'",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name_english", models.CharField(max_length=200)),
                (
                    "name_telugu",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "name_hindi",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("description_telugu", models.TextField(blank=True, default="")),
                ("description_hindi", models.TextField(blank=True, default="")),
                (
                    "typical_severity",
                    models.CharField(
                        choices=[
                            ("mild", "Mild"),
                            ("moderate", "Moderate"),
                            ("severe", "Severe"),
                            ("critical", "Critical"),
                        ],
                        default="moderate",
                        max_length=10,
                    ),
                ),
                (
                    "recommended_specialist",
                    models.CharField(
                        choices=[
                            ("general", "General Physician"),
                            ("cardiologist", "Cardiologist"),
                            ("pulmonologist", "Pulmonologist"),
                            ("gastroenterologist", "Gastroenterologist"),
                            ("neurologist", "Neurologist"),
                            ("dermatologist", "Dermatologist"),
                            ("orthopedic", "Orthopedic"),
                            ("ent", "ENT Specialist"),
                            ("ophthalmologist", "Ophthalmologist"),
                            ("psychiatrist", "Psychiatrist"),
                            ("gynecologist", "Gynecologist"),
                            ("urologist", "Urologist"),
                            ("pediatrician", "Pediatrician"),
                            ("endocrinologist", "Endocrinologist"),
                            ("infectious", "Infectious Disease Specialist"),
                            ("emergency", "Emergency Care"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "precaution_1",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_2",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_3",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_4",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_1_telugu",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_2_telugu",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_3_telugu",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_4_telugu",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_1_hindi",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_2_hindi",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_3_hindi",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "precaution_4_hindi",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "requires_immediate_care",
                    models.BooleanField(
                        default=False, help_text="If True, show emergency warning"
                    ),
                ),
                ("is_contagious", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Disease",
                "verbose_name_plural": "Diseases",
                "db_table": "diagnosis_diseases",
                "ordering": ["name_english"],
            },
        ),
        migrations.CreateModel(
            name="DiseaseSymptomMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        default=0.5,
                        help_text="Probability that this symptom indicates this disease",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary symptoms are key indicators"
                    ),
                ),
            ],
            options={
                "verbose_name": "Disease-Symptom Mapping",
                "verbose_name_plural": "Disease-Symptom Mappings",
                "db_table": "diagnosis_disease_symptom_mapping",
            },
        ),
        migrations.CreateModel(
            name="MLModelMetadata",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "model_type",
                    models.CharField(
                        choices=[
                            ("symptom_extractor", "Symptom Extractor (NER)"),
                            ("disease_predictor", "Disease Predictor"),
                            ("severity_assessor", "Severity Assessor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(max_length=20)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "model_file_path",
                    models.CharField(
                        help_text="Path to saved model file (.pkl, .joblib, etc.)",
                        max_length=500,
                    ),
                ),
                ("accuracy", models.FloatField(default=0.0)),
                ("precision", models.FloatField(default=0.0)),
                ("recall", models.FloatField(default=0.0)),
                ("f1_score", models.FloatField(default=0.0)),
                ("training_samples", models.PositiveIntegerField(default=0)),
                ("training_duration_seconds", models.PositiveIntegerField(default=0)),
                ("trained_at", models.DateTimeField()),
                (
                    "hyperparameters",
                    models.JSONField(
                        default=dict,
                        help_text="Model hyperparameters used during training",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Only one model per type should be active",
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "ML Model",
                "verbose_name_plural": "ML Models",
                "db_table": "diagnosis_ml_models",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique code like 'itching', 'skin_rash', etc.",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("name_english", models.CharField(max_length=200)),
                (
                    "name_telugu",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "name_hindi",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("description_telugu", models.TextField(blank=True, default="")),
                ("description_hindi", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("respiratory", "Respiratory"),
                            ("digestive", "Digestive"),
                            ("cardiovascular", "Cardiovascular"),
                            ("neurological", "Neurological"),
                            ("musculoskeletal", "Musculoskeletal"),
                            ("skin", "Skin"),
                            ("mental", "Mental Health"),
                            ("urinary", "Urinary"),
                            ("eye", "Eye"),
                            ("ear", "Ear"),
                            ("reproductive", "Reproductive"),
                            ("other", "Other"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "severity_weight",
                    models.IntegerField(
                        default=1,
                        help_text="Severity weight 1-7 (from dataset)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                    ),
                ),
                (
                    "keywords_english",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternative words/phrases for this symptom",
                    ),
                ),
                ("keywords_telugu", models.JSONField(blank=True, default=list)),
                ("keywords_hindi", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Symptom",
                "verbose_name_plural": "Symptoms",
                "db_table": "diagnosis_symptoms",
                "ordering": ["name_english"],
            },
        ),
        migrations.CreateModel(
            name="SymptomSynonym",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("phrase", models.CharField(max_length=200)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                ("is_common", models.BooleanField(default=False)),
                (
                    "symptom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="diagnosis.symptom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Symptom Synonym",
                "verbose_name_plural": "Symptom Synonyms",
                "db_table": "diagnosis_symptom_synonyms",
            },
        ),
        migrations.AddIndex(
            model_name="symptom",
            index=models.Index(fields=["code"], name="diagnosis_s_code_5d7e6f_idx"),
        ),
        migrations.AddIndex(
            model_name="symptom",
            index=models.Index(
                fields=["category"], name="diagnosis_s_categor_258531_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="symptom",
            index=models.Index(
                fields=["severity_weight"], name="diagnosis_s_severit_7497e0_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="mlmodelmetadata",
            unique_together={("model_type", "version")},
        ),
        migrations.AddField(
            model_name="diseasesymptommapping",
            name="disease",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="symptom_mappings",
                to="diagnosis.disease",
            ),
        ),
        migrations.AddField(
            model_name="diseasesymptommapping",
            name="symptom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="disease_mappings",
                to="diagnosis.symptom",
            ),
        ),
        migrations.AddField(
            model_name="disease",
            name="symptoms",
            field=models.ManyToManyField(
                related_name="diseases",
                through="diagnosis.DiseaseSymptomMapping",
                to="diagnosis.symptom",
            ),
        ),
        migrations.AddField(
            model_name="diagnosissession",
            name="actual_disease",
            field=models.ForeignKey(
                blank=True,
                help_text="Actual diagnosis confirmed by doctor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="confirmed_diagnoses",
                to="diagnosis.disease",
            ),
        ),
        migrations.AddField(
            model_name="diagnosissession",
            name="top_prediction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="top_predictions",
                to="diagnosis.disease",
            ),
        ),
        migrations.AddField(
            model_name="diagnosissession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnosis_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="symptomsynonym",
            index=models.Index(fields=["phrase"], name="diagnosis_s_phrase_a262c9_idx"),
        ),
        migrations.AddIndex(
            model_name="symptomsynonym",
            index=models.Index(
                fields=["language"], name="diagnosis_s_languag_aebc40_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="symptomsynonym",
            unique_together={("symptom", "phrase", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="diseasesymptommapping",
            unique_together={("disease", "symptom")},
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(fields=["code"], name="diagnosis_d_code_b79f1e_idx"),
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(
                fields=["typical_severity"], name="diagnosis_d_typical_e19c66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(
                fields=["recommended_specialist"], name="diagnosis_d_recomme_6cd055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(fields=["user"], name="diagnosis_s_user_id_7970ac_idx"),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["session_id"], name="diagnosis_s_session_4aea5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["created_at"], name="diagnosis_s_created_a13667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["severity_level"], name="diagnosis_s_severit_4a5b4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["user_feedback"], name="diagnosis_s_user_fe_1b9896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["input_language"], name="diagnosis_s_input_l_ad459c_idx"
            ),
        ),
    ]
