# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("diagnosis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="diagnosissession",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="diagnosis_sessions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="symptomsynonym",
            index=models.Index(fields=["phrase"], name="diagnosis_s_phrase_a262c9_idx"),
        ),
        migrations.AddIndex(
            model_name="symptomsynonym",
            index=models.Index(
                fields=["language"], name="diagnosis_s_languag_aebc40_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="symptomsynonym",
            unique_together={("symptom", "phrase", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="diseasesymptommapping",
            unique_together={("disease", "symptom")},
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(fields=["code"], name="diagnosis_d_code_b79f1e_idx"),
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(
                fields=["typical_severity"], name="diagnosis_d_typical_e19c66_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="disease",
            index=models.Index(
                fields=["recommended_specialist"], name="diagnosis_d_recomme_6cd055_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(fields=["user"], name="diagnosis_s_user_id_7970ac_idx"),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["session_id"], name="diagnosis_s_session_4aea5d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["created_at"], name="diagnosis_s_created_a13667_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["severity_level"], name="diagnosis_s_severit_4a5b4a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["user_feedback"], name="diagnosis_s_user_fe_1b9896_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="diagnosissession",
            index=models.Index(
                fields=["input_language"], name="diagnosis_s_input_l_ad459c_idx"
            ),
        ),
    ]
