# Generated by Django 4.2.17 on 2026-01-25 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Auto-generated title based on first message",
                        max_length=255,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "context_summary",
                    models.TextField(
                        blank=True,
                        help_text="Summarized context for long conversations",
                    ),
                ),
                (
                    "last_intent",
                    models.CharField(
                        blank=True,
                        help_text="Last detected intent (symptoms, appointment, emergency, general)",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("total_tokens_used", models.IntegerField(default=0)),
                (
                    "linked_diagnosis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="diagnosis.diagnosissession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_sessions",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Health"),
                            ("symptoms", "Symptoms"),
                            ("medicine", "Medicine"),
                            ("appointment", "Appointments"),
                            ("emergency", "Emergency"),
                            ("app_usage", "App Usage"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("question_en", models.TextField()),
                ("question_te", models.TextField(blank=True)),
                ("question_hi", models.TextField(blank=True)),
                ("answer_en", models.TextField()),
                ("answer_te", models.TextField(blank=True)),
                ("answer_hi", models.TextField(blank=True)),
                (
                    "keywords",
                    models.JSONField(
                        default=list, help_text="Keywords for FAQ matching"
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0, help_text="Higher priority = shown first"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("view_count", models.IntegerField(default=0)),
                ("helpful_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "FAQ",
                "verbose_name_plural": "FAQs",
                "db_table": "chatbot_faqs",
                "ordering": ["-priority", "category"],
            },
        ),
        migrations.CreateModel(
            name="HealthTip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition"),
                            ("exercise", "Exercise"),
                            ("mental_health", "Mental Health"),
                            ("hygiene", "Hygiene"),
                            ("seasonal", "Seasonal"),
                            ("maternal", "Maternal Health"),
                            ("child", "Child Health"),
                            ("elderly", "Elderly Care"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("title_en", models.CharField(max_length=255)),
                ("title_te", models.CharField(blank=True, max_length=255)),
                ("title_hi", models.CharField(blank=True, max_length=255)),
                ("content_en", models.TextField()),
                ("content_te", models.TextField(blank=True)),
                ("content_hi", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "show_date",
                    models.DateField(
                        blank=True,
                        help_text="Specific date to show this tip",
                        null=True,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "chatbot_health_tips",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuickReply",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context",
                    models.CharField(
                        choices=[
                            ("start", "Session Start"),
                            ("symptoms", "After Symptoms Discussion"),
                            ("appointment", "After Appointment"),
                            ("diagnosis", "After Diagnosis"),
                            ("emergency", "Emergency Context"),
                            ("general", "General"),
                        ],
                        default="general",
                        max_length=30,
                    ),
                ),
                ("text_en", models.CharField(max_length=100)),
                ("text_te", models.CharField(blank=True, max_length=100)),
                ("text_hi", models.CharField(blank=True, max_length=100)),
                (
                    "triggers_intent",
                    models.CharField(
                        blank=True,
                        help_text="Intent this reply should trigger",
                        max_length=30,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon name (e.g., 'symptoms', 'doctor', 'medicine')",
                        max_length=50,
                    ),
                ),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "chatbot_quick_replies",
                "ordering": ["context", "-priority"],
            },
        ),
        migrations.CreateModel(
            name="ConversationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.IntegerField(help_text="Overall satisfaction 1-5"),
                ),
                (
                    "helpfulness_rating",
                    models.IntegerField(
                        blank=True, help_text="How helpful was the chatbot", null=True
                    ),
                ),
                (
                    "ease_of_use_rating",
                    models.IntegerField(
                        blank=True, help_text="How easy was it to use", null=True
                    ),
                ),
                ("feedback_text", models.TextField(blank=True)),
                ("liked_aspects", models.JSONField(blank=True, default=list)),
                ("improvement_suggestions", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_conversation_feedback",
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "User"),
                            ("assistant", "Assistant"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("voice", "Voice"),
                            ("quick_reply", "Quick Reply"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(help_text="Original message content")),
                (
                    "content_translated",
                    models.TextField(
                        blank=True,
                        help_text="Translated content (to/from English for AI)",
                    ),
                ),
                ("original_language", models.CharField(default="en", max_length=5)),
                (
                    "voice_audio_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to voice recording (Supabase Storage)",
                    ),
                ),
                ("voice_duration_seconds", models.FloatField(blank=True, null=True)),
                (
                    "detected_intent",
                    models.CharField(
                        choices=[
                            ("symptoms", "Symptoms Discussion"),
                            ("appointment", "Appointment Booking"),
                            ("emergency", "Emergency"),
                            ("medicine", "Medicine Inquiry"),
                            ("general", "General Health"),
                            ("greeting", "Greeting"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=30,
                    ),
                ),
                (
                    "intent_confidence",
                    models.FloatField(default=0.0, help_text="Confidence score 0-1"),
                ),
                (
                    "extracted_entities",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Extracted entities like symptoms, dates, etc.",
                    ),
                ),
                (
                    "model_used",
                    models.CharField(
                        blank=True, help_text="Azure OpenAI model used", max_length=50
                    ),
                ),
                ("tokens_used", models.IntegerField(default=0)),
                (
                    "response_time_ms",
                    models.IntegerField(
                        default=0, help_text="Response generation time in milliseconds"
                    ),
                ),
                (
                    "feedback_rating",
                    models.IntegerField(
                        blank=True, help_text="User rating 1-5", null=True
                    ),
                ),
                ("feedback_text", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "db_table": "chatbot_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["user", "-updated_at"], name="chatbot_ses_user_id_6eb56f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(fields=["status"], name="chatbot_ses_status_3cc658_idx"),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "created_at"], name="chatbot_mes_session_0061fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["detected_intent"], name="chatbot_mes_detecte_8bcaf1_idx"
            ),
        ),
    ]
