# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("chatbot", "0001_initial"),
        ("diagnosis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="linked_diagnosis",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chat_sessions",
                to="diagnosis.diagnosissession",
            ),
        ),
    ]
