# Generated by Django 4.2.17 on 2026-01-27 06:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("medicine", "0001_initial"),
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "consultation_type",
                    models.CharField(
                        choices=[
                            ("video", "Video Call"),
                            ("audio", "Audio Call"),
                            ("chat", "Chat Only"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Scheduled"),
                            ("waiting_room", "Patient in Waiting Room"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                            ("technical_issue", "Technical Issue"),
                        ],
                        db_index=True,
                        default="scheduled",
                        max_length=20,
                    ),
                ),
                ("scheduled_start", models.DateTimeField(db_index=True)),
                ("scheduled_end", models.DateTimeField()),
                ("actual_start", models.DateTimeField(blank=True, null=True)),
                ("actual_end", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_duration",
                    models.PositiveSmallIntegerField(
                        default=15, help_text="Estimated duration in minutes"
                    ),
                ),
                (
                    "actual_duration",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Actual duration in minutes", null=True
                    ),
                ),
                (
                    "reason",
                    models.TextField(blank=True, help_text="Reason for consultation"),
                ),
                (
                    "symptoms",
                    models.TextField(
                        blank=True,
                        help_text="Patient's symptoms (from diagnosis app or manual)",
                    ),
                ),
                (
                    "diagnosis",
                    models.TextField(blank=True, help_text="Doctor's diagnosis"),
                ),
                ("follow_up_required", models.BooleanField(default=False)),
                ("follow_up_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancellation_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("te", "Telugu"), ("hi", "Hindi")],
                        default="en",
                        max_length=5,
                    ),
                ),
                (
                    "appointment",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation",
                        to="appointments.appointment",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_consultations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation",
                "verbose_name_plural": "Consultations",
                "db_table": "consultations",
                "ordering": ["-scheduled_start"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationRoom",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "room_name",
                    models.CharField(db_index=True, max_length=100, unique=True),
                ),
                (
                    "room_password",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "jitsi_domain",
                    models.CharField(
                        default="meet.jit.si",
                        help_text="Jitsi server domain (default: meet.jit.si - FREE)",
                        max_length=255,
                    ),
                ),
                ("is_audio_only", models.BooleanField(default=False)),
                (
                    "is_lobby_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Patients wait in lobby until doctor admits",
                    ),
                ),
                ("max_participants", models.PositiveSmallIntegerField(default=2)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("waiting", "Waiting for Participants"),
                            ("active", "Active"),
                            ("ended", "Ended"),
                            ("expired", "Expired"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        help_text="Room expires if not used by this time"
                    ),
                ),
                ("doctor_joined_at", models.DateTimeField(blank=True, null=True)),
                ("patient_joined_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Consultation Room",
                "verbose_name_plural": "Consultation Rooms",
                "db_table": "consultation_rooms",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationPrescription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "medicine_name",
                    models.CharField(
                        help_text="Medicine name (used if not linked to Medicine model)",
                        max_length=200,
                    ),
                ),
                (
                    "dosage",
                    models.CharField(help_text="e.g., '500mg', '10ml'", max_length=100),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="e.g., 'Twice daily', 'Every 8 hours'", max_length=100
                    ),
                ),
                (
                    "duration",
                    models.CharField(
                        help_text="e.g., '7 days', '2 weeks'", max_length=100
                    ),
                ),
                (
                    "timing",
                    models.CharField(
                        choices=[
                            ("before_food", "Before Food"),
                            ("after_food", "After Food"),
                            ("with_food", "With Food"),
                            ("empty_stomach", "Empty Stomach"),
                            ("bedtime", "At Bedtime"),
                            ("any_time", "Any Time"),
                        ],
                        default="after_food",
                        max_length=20,
                    ),
                ),
                (
                    "instructions",
                    models.TextField(
                        blank=True, help_text="Special instructions for the patient"
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of units to dispense"
                    ),
                ),
                ("refills_allowed", models.PositiveSmallIntegerField(default=0)),
                ("refills_used", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "medicine",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation_prescriptions",
                        to="medicine.medicine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Prescription",
                "verbose_name_plural": "Consultation Prescriptions",
                "db_table": "consultation_prescriptions",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationNote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[
                            ("subjective", "Subjective (Patient Complaints)"),
                            ("objective", "Objective (Observations)"),
                            ("assessment", "Assessment (Diagnosis)"),
                            ("plan", "Plan (Treatment Plan)"),
                            ("general", "General Notes"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "is_private",
                    models.BooleanField(
                        default=False,
                        help_text="Private notes are only visible to the doctor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="consultation.consultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Note",
                "verbose_name_plural": "Consultation Notes",
                "db_table": "consultation_notes",
                "ordering": ["note_type", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "communication_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "technical_quality_rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Audio/Video quality",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comments", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(blank=True, null=True)),
                ("had_technical_issues", models.BooleanField(default=False)),
                ("technical_issue_description", models.TextField(blank=True)),
                (
                    "is_anonymous",
                    models.BooleanField(
                        default=False,
                        help_text="If true, patient name hidden from doctor",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="consultation.consultation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Feedback",
                "verbose_name_plural": "Consultation Feedbacks",
                "db_table": "consultation_feedbacks",
            },
        ),
        migrations.CreateModel(
            name="ConsultationAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("report", "Medical Report"),
                            ("prescription", "Prescription"),
                            ("lab_result", "Lab Result"),
                            ("scan", "Scan/X-Ray"),
                            ("photo", "Photo"),
                            ("document", "Other Document"),
                        ],
                        default="document",
                        max_length=20,
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                (
                    "file_url",
                    models.URLField(
                        help_text="URL to file (stored in Supabase Storage)"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="consultation.consultation",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_uploads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Attachment",
                "verbose_name_plural": "Consultation Attachments",
                "db_table": "consultation_attachments",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="consultation",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="consultation.consultationroom",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["doctor", "status"], name="consultatio_doctor__fd2d75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["patient", "status"], name="consultatio_patient_45acff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["scheduled_start", "status"],
                name="consultatio_schedul_7d2c08_idx",
            ),
        ),
    ]
