# Generated by Django 4.2.17 on 2026-03-11 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "0002_initial"),
        ("consultation", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationattachment",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultation",
                to="appointments.appointment",
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="doctor_consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="patient",
            field=models.ForeignKey(
                limit_choices_to={"role": "patient"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="patient_consultations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="consultation",
            name="room",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="consultation",
                to="consultation.consultationroom",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationprescription",
            index=models.Index(
                fields=["consultation", "is_active"],
                name="consultatio_consult_8603ca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationnote",
            index=models.Index(
                fields=["consultation", "note_type"],
                name="consultatio_consult_08162a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationattachment",
            index=models.Index(
                fields=["consultation", "attachment_type"],
                name="consultatio_consult_a39c07_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["doctor", "status"], name="consultatio_doctor__fd2d75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["patient", "status"], name="consultatio_patient_45acff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["scheduled_start", "status"],
                name="consultatio_schedul_7d2c08_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["doctor", "scheduled_start"],
                name="consultatio_doctor__121a41_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["patient", "scheduled_start"],
                name="consultatio_patient_35ec3e_idx",
            ),
        ),
    ]
