# Generated by Django 4.2.17 on 2026-04-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultation", "0002_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="consultationnote",
            index=models.Index(
                fields=["consultation", "created_at"],
                name="consultatio_consult_680a65_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultationprescription",
            index=models.Index(
                fields=["consultation", "created_at"],
                name="consultatio_consult_3124a8_idx",
            ),
        ),
    ]
